#!/usr/bin/env python3
"""The car, batched, on the Obstacle Course's real surfaces.

The planar part is rl/formulaOne/plant.py's actuation chain, unchanged in
substance -- bridge speed slew, closed-loop speed with no brakes, measured
asymmetric steering, servo lag, chassis yaw lag, understeer and tire scrub,
per-episode domain randomization -- because that chain is what made a policy
trained in numpy drive Gazebo's Speed Course.

Reverse follows the Arduino's SpeedController (README, Speed Control) and
the 2026-09 characterization (docs/characterization-results.md): the
tachometer cannot see direction, so a reverse target while rolling forward
is tracked as zero and the car COASTS -- there is no braking (every Brake
Limit tried stopped the car slower than coasting, section 3).  The
direction changes once the wheels read stopped: the tachometer times out
0.4 s after the car drops under its 0.3 m/s floor, and the controller waits
0.1 s more (`reverse_wait`, 0.5 s from the floor).  Coast drag and the
feedforward are the same both ways (3% apart, sections 1-2), so reverse
drives on the forward curves.  The same holds going from reverse to forward.

Touching an obstacle does not end the car.  The chassis is checked every
other substep; a car that has moved into something is put back where it was
clear and slides along whichever axis of its motion stays clear, keeping the
share of its speed that motion carries (a glancing touch on the course's
axis-aligned walls costs little, a head-on one stops it).  The speed lost is
reported, and the env decides what counts as a crash.

What this adds is the third dimension, because the obstacle course is not
flat and the car does not stay level on it:

  * A SPRUNG BODY with heave, pitch and roll on four corner spring-dampers,
    with the Gazebo vehicle's own numbers (worlds/obstacle_course.sdf,
    generated by generate_vehicle_model.py): k 239/272 N/m, c 12.7/14.5
    N s/m front/rear, travel -0.014..+0.036 m about the ride height, the
    spring preloaded so the car rests at q = 0, stiff bump stops past it.
  * RIGID TIRES on the baked collision surface.  Each corner's wheel center
    is where a 0.0566 m circle rests on the ground under its contact chord
    (course_model.support_below sampled across the chord), so a tire rolls up
    a lip, dips part way into an 18 mm pothole recess narrower than itself,
    and climbs the 19 mm bumps -- and that height, not a flattened grade,
    drives the suspension.
  * UNILATERAL CONTACT.  A corner whose spring would have to pull is off the
    ground: over the ramp crest, the deck-to-helix seam, the bump domes.  A
    wheel off the ground carries no load, and traction is mu times load, so
    it neither drives nor steers the car.
  * GRADE AND BANK FORCES.  Longitudinally, each loaded tire resists climbing
    in proportion to its load and the slope its center is being lifted at --
    the 19% ramp, the 11% helix and its segment seams, the lips and bumps.
    Laterally, the ground's roll puts g sin(roll) across the car, which the
    tires hold only up to mu times load; past that the car slides.
  * FRICTION from the surface under each tire: 0.35 on the gravel lid and
    pebbles against 1.0 elsewhere (ODE uses the lower of tire and ground mu).

The body attitude is returned to the env, which puts the camera where the body
has put it and feeds the segmenter-leveling model the attitude the IMU would
report.
"""

from __future__ import annotations

import math

import numba as nb
import numpy as np

import course_model

G = 9.81

# Vehicle geometry and suspension, from worlds/obstacle_course.sdf.
WHEEL_RADIUS = 0.0566
HALF_WHEELBASE = 0.162
HALF_TRACK = 0.145
TIRE_WIDTH = 0.035
SPRUNG_MASS = 2.899
UNSPRUNG_MASS = 0.175  # upright + knuckle + wheel, per corner (front; rear 0.15)
TOTAL_MASS = 3.599
CG_X = -0.0202
CG_Z = 0.067
I_ROLL = 0.08
I_PITCH = 0.12
SPRING = np.array([239.0, 239.0, 272.0, 272.0])  # FL FR RL RR
DAMPING = np.array([12.7, 12.7, 14.5, 14.5])
TRAVEL_DROOP = -0.014
TRAVEL_BUMP = 0.036
BUMP_STOP = 30000.0
BUMP_STOP_DAMPING = 60.0
CORNER_X = np.array([HALF_WHEELBASE, HALF_WHEELBASE, -HALF_WHEELBASE, -HALF_WHEELBASE])
CORNER_Y = np.array([HALF_TRACK, -HALF_TRACK, HALF_TRACK, -HALF_TRACK])
# Chassis collision box (chassis frame): 0.55 x 0.30 x 0.12 at z 0.094.  The
# tires stand 12.5 mm proud of it at the sides, so contact uses their width.
BODY_HALF_LENGTH = 0.275
BODY_HALF_WIDTH = 0.1625
BODY_BOTTOM = 0.034
BODY_TOP = 0.154

# Slip relaxation: how fast lateral velocity dies when the tires can hold it.
SLIP_TAU = 0.05
# Largest force one corner can put into the body, N (about 12 g on a corner).
MAX_CORNER_FORCE = 100.0
# Past this the car is on its side or its roof.
ROLLOVER_RAD = 0.8


def _spring_reference():
    """Per-corner spring reference that rests the car at q = 0.

    generate_vehicle_model.py: the sprung corner load over the rate, negative,
    from the chassis CG's front/rear split.
    """
    wheelbase = 2 * HALF_WHEELBASE
    front = 0.5 + CG_X / wheelbase
    load = SPRUNG_MASS * G * np.array([front, front, 1 - front, 1 - front]) / 2.0
    return -load / SPRING


SPRING_REF = _spring_reference()

# State layout: one float64 row per car.
S_X, S_Y, S_YAW, S_V, S_VY, S_R = 0, 1, 2, 3, 4, 5
S_Z, S_VZ, S_PITCH, S_PITCH_RATE, S_ROLL, S_ROLL_RATE = 6, 7, 8, 9, 10, 11
S_STEER, S_TARGET = 12, 13
S_Q = 14  # 4 suspension positions
S_W = 18  # 4 wheel-center heights last substep
S_LOAD = 22  # 4 normal loads
S_GROUND_PITCH, S_GROUND_ROLL = 26, 27
S_SCRAPE = 28  # chassis-on-road contact this step (bottoming out)
S_DIR = 29  # +1 driving forward, -1 in reverse (the controller's belief)
S_STOP_T = 30  # time the wheels have read stopped
N_STATE = 31

# Parameter layout: one float64 row per car, drawn per episode.
P_DEAD, P_F0, P_F1, P_ACCEL, P_SLEW, P_UNDER, P_SCRUB = 0, 1, 2, 3, 4, 5, 6
P_GAIN, P_ASYM, P_OFFSET, P_LIMIT, P_DROPOUT, P_YAW_TAU, P_STEER_TAU = (
    7,
    8,
    9,
    10,
    11,
    12,
    13,
)
P_MU_SCALE, P_SPRING_SCALE, P_DAMP_SCALE = 14, 15, 16
P_REV_WAIT = 17
N_PARAM = 18
# The tachometer's floor: below it no revolution arrives inside the 400 ms
# timeout, and reverse_wait counts from here.
STOPPED_V = 0.30


@nb.njit(cache=True)
def _wheel_center(SUP, lay, x, y, heading, axle_z):
    """Height a rigid tire's center rests at, over the collision surface.

    Samples the ground across the contact chord and takes the highest
    resting center.  Surfaces above the axle are not road
    to this wheel (a wall to it, or a deck over it), and neither is anything
    more than one radius below it that the sample happens to find.
    Returns (center height, mu under the highest point).
    """
    c = math.cos(heading)
    s = math.sin(heading)
    best = -1e9
    best_mu = 1.0
    probe = axle_z + 0.01
    for a in range(-4, 5):
        dx = a * WHEEL_RADIUS / 4.5
        rise = math.sqrt(max(WHEEL_RADIUS * WHEEL_RADIUS - dx * dx, 0.0))
        top, mu = course_model.support_smooth(SUP, lay, x + dx * c, y + dx * s, probe)
        h = top + rise
        if h > best:
            best = h
            best_mu = mu
    return best, best_mu


@nb.njit(cache=True)
def _steer_angle(cmd, p):
    c = min(max(cmd + p[P_OFFSET], -1.0), 1.0)
    # Measured table [-1, -0.5, 0, 0.5, 1] -> [-0.382, -0.191, 0, 0.256, 0.512].
    if c < 0:
        a = 0.382 * c
    else:
        a = 0.512 * c
    a *= p[P_GAIN]
    if a > 0:
        a *= p[P_ASYM]
    return min(max(a, -p[P_LIMIT]), p[P_LIMIT])


@nb.njit(cache=True)
def _car_substep(SUP, L, s, q, steer_cmd, speed_cmd, dt, max_speed, steer_slew):
    """Advance one car by dt under the command reaching its wheels now."""
    v = s[S_V]
    yaw = s[S_YAW]
    c = math.cos(yaw)
    sn = math.sin(yaw)

    # ---- vertical: corners on the ground, springs, body ----
    total_load = 0.0
    grade_force = 0.0
    mu_load = 0.0
    forces = np.zeros(4)
    for i in range(4):
        cx = CORNER_X[i]
        cy = CORNER_Y[i]
        # Corner attachment height, chassis frame z = 0 at the corner.
        zc = s[S_Z] + cx * math.sin(s[S_PITCH]) + cy * math.sin(s[S_ROLL])
        wx = s[S_X] + cx * c - cy * sn
        wy = s[S_Y] + cx * sn + cy * c
        axle = zc + WHEEL_RADIUS + s[S_Q + i]
        w, mu = _wheel_center(SUP, L, wx, wy, yaw, axle)
        qi = w - (zc + WHEEL_RADIUS)
        qdot = (qi - s[S_Q + i]) / dt
        k_s = SPRING[i] * q[P_SPRING_SCALE]
        c_s = DAMPING[i] * q[P_DAMP_SCALE]
        f = 0.0
        if qi >= TRAVEL_DROOP:
            f = k_s * (qi - SPRING_REF[i]) + c_s * qdot
            if qi > TRAVEL_BUMP:
                f += BUMP_STOP * (qi - TRAVEL_BUMP) + BUMP_STOP_DAMPING * qdot
            # A tire can only push, and never harder than a hard landing:
            # this bounds the impulse when a wheel meets a step it should
            # not have been able to reach (the body contact ends that
            # episode anyway), so the integration cannot run away.
            f = min(max(f, 0.0), MAX_CORNER_FORCE)
        if f > 0.0:
            s[S_Q + i] = min(qi, TRAVEL_BUMP + 0.02)
            load = f + UNSPRUNG_MASS * G
        else:
            # Off the ground: the wheel hangs at full droop.
            s[S_Q + i] = TRAVEL_DROOP
            load = 0.0
        forces[i] = f
        # How steeply this tire's center is being lifted per meter of
        # travel: the slope it is climbing, including lips and bumps.
        if load > 0.0 and abs(v) > 0.05:
            slope = (w - s[S_W + i]) / (abs(v) * dt)
            slope = min(max(slope, -3.0), 3.0)
            grade_force += load * slope
        s[S_W + i] = w
        s[S_LOAD + i] = load
        total_load += load
        mu_load += load * mu * q[P_MU_SCALE]

    a_x_body = 0.0
    a_y_body = v * s[S_R]
    # Ground attitude from the four wheel centers.
    w_front = 0.5 * (s[S_W] + s[S_W + 1])
    w_rear = 0.5 * (s[S_W + 2] + s[S_W + 3])
    w_left = 0.5 * (s[S_W] + s[S_W + 2])
    w_right = 0.5 * (s[S_W + 1] + s[S_W + 3])
    s[S_GROUND_PITCH] = math.atan2(w_front - w_rear, 2 * HALF_WHEELBASE)
    s[S_GROUND_ROLL] = math.atan2(w_left - w_right, 2 * HALF_TRACK)

    # ---- longitudinal: bridge slew, closed-loop speed, no brakes ----
    want = min(max(speed_cmd, -max_speed), max_speed)
    step = q[P_SLEW] * dt
    s[S_TARGET] += min(max(want - s[S_TARGET], -step), step)
    # Direction: the controller keeps the direction it last drove, and a
    # target the other way is a zero target until the wheels read stopped.
    if abs(v) < STOPPED_V:
        s[S_STOP_T] += dt
    else:
        s[S_STOP_T] = 0.0
    d = s[S_DIR]
    against = s[S_TARGET] * d < 0.0
    if against and s[S_STOP_T] >= q[P_REV_WAIT]:
        d = -d
        s[S_DIR] = d
        against = False
    # Speed in the driving direction, u >= 0.
    u = max(v * d, 0.0)
    target_u = 0.0 if against else s[S_TARGET] * d
    # The motor pushes only through loaded tires.
    traction = mu_load / TOTAL_MASS
    accel_limit = min(q[P_ACCEL], traction)
    coast = q[P_F0] + q[P_F1] * u
    delta = target_u - u
    if total_load <= 0.0:
        du = -coast * dt  # airborne: nothing to push on
    elif delta > 0:
        du = min(delta, accel_limit * dt)
    else:
        du = max(delta, -coast * dt)
    # Climbing (or descending) resistance, from the loaded tires.
    du -= grade_force / TOTAL_MASS * dt
    u_new = min(max(u + du, 0.0), max_speed)
    v_new = u_new * d
    a_x_body = (v_new - v) / dt
    v = v_new
    s[S_V] = v

    # ---- steering servo ----
    want_angle = _steer_angle(steer_cmd, q)
    slew = steer_slew * dt
    reach = s[S_STEER] + min(max(want_angle - s[S_STEER], -slew), slew)
    alpha = dt / (q[P_STEER_TAU] + dt)
    s[S_STEER] += alpha * (reach - s[S_STEER])

    # ---- yaw and lateral: bicycle, lagged, within the friction circle ----
    cap = mu_load / TOTAL_MASS
    eff_wb = (2 * HALF_WHEELBASE + q[P_UNDER] * v * v) * q[P_SCRUB]
    kin = v * math.tan(s[S_STEER]) / eff_wb
    if total_load > 0.0:
        beta = dt / (q[P_YAW_TAU] + dt)
        s[S_R] += beta * (kin - s[S_R])
        # The tires cannot hold more than mu * load of cornering.
        if abs(v) > 0.1:
            lim = cap / abs(v)
            s[S_R] = min(max(s[S_R], -lim), lim)
    # Gravity across the car on a rolled surface (the bank).
    a_g = -G * math.sin(s[S_GROUND_ROLL])
    need = v * s[S_R] - a_g - s[S_VY] / SLIP_TAU
    a_tire = min(max(need, -cap), cap)
    s[S_VY] += (a_g + a_tire - v * s[S_R]) * dt
    a_y_body = a_g + a_tire

    # ---- plan motion ----
    vh = v * math.cos(s[S_GROUND_PITCH])
    s[S_YAW] = yaw + s[S_R] * dt
    s[S_X] += (vh * c - s[S_VY] * sn) * dt
    s[S_Y] += (vh * sn + s[S_VY] * c) * dt

    # ---- body: heave, pitch, roll ----
    f_sum = forces[0] + forces[1] + forces[2] + forces[3]
    m_pitch = 0.0
    m_roll = 0.0
    for i in range(4):
        m_pitch += forces[i] * (CORNER_X[i] - CG_X)
        m_roll += forces[i] * CORNER_Y[i]
    # Tire forces act at the ground, below the CG: accelerating squats the
    # rear, cornering rolls the body outboard.
    m_pitch += SPRUNG_MASS * a_x_body * CG_Z
    m_roll += SPRUNG_MASS * a_y_body * CG_Z
    s[S_VZ] += (f_sum / SPRUNG_MASS - G) * dt
    s[S_PITCH_RATE] += m_pitch / I_PITCH * dt
    s[S_ROLL_RATE] += m_roll / I_ROLL * dt
    s[S_Z] += s[S_VZ] * dt
    s[S_PITCH] += s[S_PITCH_RATE] * dt
    s[S_ROLL] += s[S_ROLL_RATE] * dt


@nb.njit(cache=True)
def substep(SUP, lay, st, p, steer_cmd, speed_cmd, dt, max_speed, steer_slew):
    """Advance every car by dt (serial; tests and settling)."""
    for k in range(st.shape[0]):
        _car_substep(
            SUP,
            lay[k],
            st[k],
            p[k],
            steer_cmd[k],
            speed_cmd[k],
            dt,
            max_speed,
            steer_slew,
        )


@nb.njit(cache=True, parallel=True)
def control_period(
    SUP,
    OBS,
    lay,
    st,
    p,
    hist,
    head,
    steer,
    speed,
    substeps,
    dt,
    max_speed,
    steer_slew,
    check_every,
):
    """One control period for every car, in parallel.

    The command enters each car's history now and reaches its wheels
    `dead_time` later; the chassis is checked against obstacles every
    `check_every` substeps, and a car found inside something is put back
    (`_resolve_contact`).  Returns (touched, speed lost to contact, rolled).
    """
    n = st.shape[0]
    hlen = hist.shape[1]
    touched = np.zeros(n, np.bool_)
    lost = np.zeros(n)
    rolled = np.zeros(n, np.bool_)
    for k in nb.prange(n):
        delay = min(max(int(p[k, P_DEAD] / dt), 0), hlen - 1)
        h = head
        clear_x = st[k, S_X]
        clear_y = st[k, S_Y]
        clear_yaw = st[k, S_YAW]
        for i in range(substeps):
            hist[k, h, 0] = steer[k]
            hist[k, h, 1] = speed[k]
            j = (h - delay) % hlen
            _car_substep(
                SUP,
                lay[k],
                st[k],
                p[k],
                hist[k, j, 0],
                hist[k, j, 1],
                dt,
                max_speed,
                steer_slew,
            )
            h = (h + 1) % hlen
            if (i + 1) % check_every == 0 or i == substeps - 1:
                if _outline_hits(OBS, lay[k], st[k], 0.0, 0.03):
                    touched[k] = True
                    lost[k] += _resolve_contact(
                        OBS, lay[k], st[k], clear_x, clear_y, clear_yaw
                    )
                clear_x = st[k, S_X]
                clear_y = st[k, S_Y]
                clear_yaw = st[k, S_YAW]
        if abs(st[k, S_PITCH]) > ROLLOVER_RAD or abs(st[k, S_ROLL]) > ROLLOVER_RAD:
            rolled[k] = True
    return touched, lost, rolled


@nb.njit(cache=True)
def _resolve_contact(OBS, L, s, x0, y0, yaw0):
    """Put a car that has moved into an obstacle back, sliding if it can.

    (x0, y0, yaw0) is where it last checked clear.  Its motion since is tried
    along x alone and along y alone, the longer first, from the clear pose's
    heading; the first that stays clear is kept, with the share of the speed
    that component carries.  If neither does, it goes back to the clear pose
    and stops.  Either way the tires' sideways slip and the yaw rate die in
    the impact.  Returns the speed lost.
    """
    dx = s[S_X] - x0
    dy = s[S_Y] - y0
    d = math.hypot(dx, dy)
    v0 = abs(s[S_V])
    keep = 0.0
    fx = x0
    fy = y0
    for trial in range(2):
        along_x = (trial == 0) == (abs(dx) >= abs(dy))
        tx = x0 + dx if along_x else x0
        ty = y0 if along_x else y0 + dy
        s[S_X] = tx
        s[S_Y] = ty
        s[S_YAW] = yaw0
        if d > 1e-9 and not _outline_hits(OBS, L, s, 0.0, 0.03):
            keep = abs(dx if along_x else dy) / d
            fx = tx
            fy = ty
            break
    s[S_X] = fx
    s[S_Y] = fy
    s[S_YAW] = yaw0
    s[S_V] *= keep
    s[S_VY] = 0.0
    s[S_R] = 0.0
    return v0 - abs(s[S_V])


@nb.njit(cache=True)
def place(SUP, lay, st, reach):
    """Set each car on the road under its wheels, attitude and all.

    A car dealt part way round is given the centerline's height, which is the
    floor's on the bank, the gravel tray and the pothole board; left there it
    would start inside them.  Each wheel is dropped onto the highest surface
    within `reach` above that height instead.
    """
    for k in range(st.shape[0]):
        s = st[k]
        c = math.cos(s[S_YAW])
        sn = math.sin(s[S_YAW])
        w = np.empty(4)
        for i in range(4):
            wx = s[S_X] + CORNER_X[i] * c - CORNER_Y[i] * sn
            wy = s[S_Y] + CORNER_X[i] * sn + CORNER_Y[i] * c
            w[i], _ = _wheel_center(SUP, lay[k], wx, wy, s[S_YAW], s[S_Z] + reach)
            s[S_W + i] = w[i]
        front = 0.5 * (w[0] + w[1])
        rear = 0.5 * (w[2] + w[3])
        left = 0.5 * (w[0] + w[2])
        right = 0.5 * (w[1] + w[3])
        s[S_PITCH] = math.atan2(front - rear, 2 * HALF_WHEELBASE)
        s[S_ROLL] = math.atan2(left - right, 2 * HALF_TRACK)
        s[S_Z] = 0.25 * (w[0] + w[1] + w[2] + w[3]) - WHEEL_RADIUS + 0.003


@nb.njit(cache=True)
def settle(SUP, lay, st, p, dt, steps):
    """Drop the cars onto the surface and let the springs settle, standing."""
    n = st.shape[0]
    zero = np.zeros(n)
    for _ in range(steps):
        for k in range(n):
            st[k, S_V] = 0.0
            st[k, S_TARGET] = 0.0
        substep(SUP, lay, st, p, zero, zero, dt, 0.0, 0.0)


@nb.njit(cache=True)
def body_contact(OBS, lay, st, spacing):
    """Per car: whether the chassis (tires' width) touches an obstacle.

    Walks the body outline in the body's own attitude, so a car pitched up the
    ramp or rolled on the bank is checked where its bodywork actually is.
    """
    n = st.shape[0]
    out = np.zeros(n, np.bool_)
    for k in range(n):
        out[k] = _outline_hits(OBS, lay[k], st[k], 0.0, spacing)
    return out


@nb.njit(cache=True)
def _outline_hits(OBS, L, s, grow, spacing):
    c = math.cos(s[S_YAW])
    sn = math.sin(s[S_YAW])
    hl = BODY_HALF_LENGTH + grow
    hw = BODY_HALF_WIDTH + grow
    nl = max(2, int(2 * hl / spacing) + 1)
    nw = max(2, int(2 * hw / spacing) + 1)
    sp = math.sin(s[S_PITCH])
    sr = math.sin(s[S_ROLL])
    for side in range(4):
        count = nl if side < 2 else nw
        for a in range(count):
            f = a / (count - 1)
            if side == 0:
                bx, by = -hl + 2 * hl * f, hw
            elif side == 1:
                bx, by = -hl + 2 * hl * f, -hw
            elif side == 2:
                bx, by = hl, -hw + 2 * hw * f
            else:
                bx, by = -hl, -hw + 2 * hw * f
            z0 = s[S_Z] + bx * sp + by * sr
            px = s[S_X] + bx * c - by * sn
            py = s[S_Y] + bx * sn + by * c
            # A little below the belly: the tires reach the ground at the
            # sides, and a low rail the body clears still stops a wheel.
            if course_model.obstacle_overlap(
                OBS, L, px, py, z0 + BODY_BOTTOM - 0.02, z0 + BODY_TOP
            ):
                return True
    return False


@nb.njit(cache=True)
def body_clearance(OBS, lay, st, rings):
    """Per car: the smallest ring offset (m) at which the outline hits, else inf."""
    n = st.shape[0]
    out = np.full(n, np.inf)
    for k in range(n):
        for r in rings:
            if _outline_hits(OBS, lay[k], st[k], r, 0.03):
                out[k] = r
                break
    return out


class Plant:
    """B cars, their per-episode parameters, and the command dead time."""

    def __init__(self, cfg: dict, model, n: int, rng: np.random.Generator):
        self.cfg = cfg
        self.SUP, self.OBS, self.SEN = model.tables()
        self.n = n
        self.rng = rng
        p = cfg["plant"]
        self.max_speed = float(p["max_speed"])
        self.steer_slew = float(p["steering_slew"])
        self.dt = 1.0 / (float(cfg["env"]["control_hz"]) * int(cfg["env"]["substeps"]))
        self.hist_len = int(np.ceil(0.40 / self.dt)) + 2
        self.history = np.zeros((n, self.hist_len, 2))
        self.head = 0
        self.state = np.zeros((n, N_STATE))
        self.params = np.zeros((n, N_PARAM))
        self.lay = np.zeros(n, np.int64)
        self.last_command = np.zeros((n, 2))
        self.nominal = {
            P_DEAD: p["command_dead_time"],
            P_F0: p["coast_f0"] / p["mass"],
            P_F1: p["coast_f1"] / p["mass"],
            P_ACCEL: p["max_accel"],
            P_SLEW: p["speed_slew_rate"],
            P_UNDER: p["understeer_gradient"],
            P_SCRUB: p["tire_scrub"],
            P_GAIN: 1.0,
            P_ASYM: 1.0,
            P_OFFSET: 0.0,
            P_LIMIT: 0.512,
            P_DROPOUT: 0.0,
            P_YAW_TAU: p["yaw_response_tau"],
            P_STEER_TAU: p["steering_tau"],
            P_MU_SCALE: 1.0,
            P_SPRING_SCALE: 1.0,
            P_DAMP_SCALE: 1.0,
            P_REV_WAIT: p["reverse_wait"],
        }

    def sample_parameters(self, idx):
        r = self.cfg["randomize"]
        k = len(idx)
        u = self.rng.uniform
        for key, value in self.nominal.items():
            self.params[idx, key] = value
        if not r["enabled"]:
            return
        pr = self.params
        pr[idx, P_DEAD] = u(*r["dead_time"], k)
        pr[idx, P_YAW_TAU] *= u(*r["yaw_tau_scale"], k)
        pr[idx, P_STEER_TAU] = u(*r["steering_tau"], k)
        coast = u(*r["coast_scale"], k)
        pr[idx, P_F0] *= coast
        pr[idx, P_F1] *= coast
        pr[idx, P_ACCEL] *= u(*r["accel_scale"], k)
        pr[idx, P_SLEW] *= u(*r["slew_scale"], k)
        pr[idx, P_UNDER] = u(*r["understeer"], k)
        pr[idx, P_SCRUB] *= u(*r["scrub_scale"], k)
        pr[idx, P_GAIN] = u(*r["steer_gain"], k)
        pr[idx, P_ASYM] = u(*r["steer_asymmetry"], k)
        pr[idx, P_OFFSET] = u(*r["steer_offset"], k)
        pr[idx, P_LIMIT] = u(*r["steer_limit"], k)
        pr[idx, P_DROPOUT] = u(*r["action_dropout"], k)
        pr[idx, P_MU_SCALE] = u(*r["mu_scale"], k)
        pr[idx, P_SPRING_SCALE] = u(*r["spring_scale"], k)
        pr[idx, P_DAMP_SCALE] = u(*r["damping_scale"], k)
        pr[idx, P_REV_WAIT] = u(*r["reverse_wait"], k)

    def reset(self, idx, lay, x, y, z, yaw, speed):
        """Place cars `idx`, drop them onto the course, and settle them."""
        idx = np.asarray(idx)
        self.sample_parameters(idx)
        self.lay[idx] = lay
        st = np.zeros((len(idx), N_STATE))
        st[:, S_X], st[:, S_Y], st[:, S_YAW] = x, y, yaw
        st[:, S_Z] = z
        st[:, S_Q : S_Q + 4] = 0.0
        # Onto the road under the wheels (the bank, the gravel lid and the
        # pothole board stand up to 0.2 m above the centerline's height),
        # then let the springs take the weight.
        place(self.SUP, self.lay[idx], st, 0.25)
        settle(self.SUP, self.lay[idx], st, self.params[idx], self.dt, 120)
        st[:, S_V] = speed
        st[:, S_TARGET] = speed
        st[:, S_DIR] = 1.0
        self.state[idx] = st
        self.history[idx] = 0.0
        self.history[idx, :, 1] = (
            np.asarray(speed)[:, None] if np.ndim(speed) else speed
        )
        self.last_command[idx] = 0.0

    def push_command(self, steer, speed):
        """A command as issued now; the dead time delays it to the wheels."""
        repeat = self.rng.random(self.n) < self.params[:, P_DROPOUT]
        steer = np.where(repeat, self.last_command[:, 0], steer)
        speed = np.where(repeat, self.last_command[:, 1], speed)
        self.last_command[:, 0] = steer
        self.last_command[:, 1] = speed
        return steer, speed

    def step(self, steer, speed, substeps: int):
        """One control period; returns (touched, speed lost, rolled) per car."""
        touched, lost, rolled = control_period(
            self.SUP,
            self.OBS,
            self.lay,
            self.state,
            self.params,
            self.history,
            self.head,
            np.ascontiguousarray(steer, dtype=np.float64),
            np.ascontiguousarray(speed, dtype=np.float64),
            substeps,
            self.dt,
            self.max_speed,
            self.steer_slew,
            2,
        )
        self.head = (self.head + substeps) % self.hist_len
        return touched, lost, rolled
