#include <SoftwareSerial.h>

#include <XBee.h>

// Offboard link wire format.
//
// Both directions are packed binary, not ASCII.  The reason is interrupt
// blackout rather than bandwidth: SoftwareSerial disables interrupts for a full
// byte time (~174us at 57600) and works through a frame's bytes back to back,
// so a 50 byte ASCII command frame suppressed interrupts for nearly 9ms at a
// stretch, twenty times a second.  The hardware USART's receive buffer is two
// bytes deep and at 1Mbaud a byte lands every 10us, so every offboard frame
// used to overrun the USB link and corrupt whatever Jetson frame was in flight.
// Eight bytes cuts that window by more than six times.
//
// The XBee API frame already carries a length and a checksum, and the parser
// validates both, so the payload needs no integrity field of its own - only a
// format tag, so a mismatched firmware/offboard pair fails closed instead of
// misreading old ASCII as flags.
constexpr uint8_t OFFBOARD_CMD_TAG = 0xC1;
constexpr uint8_t OFFBOARD_CMD_LENGTH = 8;
constexpr uint8_t OFFBOARD_STATUS_TAG = 0x51;
constexpr uint8_t OFFBOARD_STATUS_LENGTH = 11;

XBee xbee;
SoftwareSerial serXBee(2, 3);
Tx16Request tx16 = Tx16Request();
uint8_t offboardTxPayload[OFFBOARD_STATUS_LENGTH] = {};
// Sized for the gains frame, by far the longest Jetson frame.
uint8_t onboardRxPayload[96] = {};
uint8_t onboardTxPayload[48] = {};
uint8_t onboardDebugPayload[160] = {};
// Bytes of a rejected Jetson frame kept for the debug line.
constexpr uint8_t REJECTED_FRAME_CAPTURE = 16;

const unsigned long commsTimeout_ms = 200;
const bool enableOffboardTx = true;
const bool enableOnboardDebug = true;

// USB serial to the Jetson.
//
// 115200 rather than 1000000 because of the same SoftwareSerial blackout as
// above, seen from the other side.  At 1Mbaud a Jetson byte lands every 10us,
// so one ~174us blackout overruns the USART's two byte buffer; on the bench
// 14% of Jetson frames arrived with bytes missing.  At 115200 a byte takes
// 868us, longer than any single blackout, and the loss fell below 1%.  Worst
// case traffic, with the tuning trace on, is ~5kB/s against the 11.5kB/s the
// link carries.
constexpr unsigned long ONBOARD_BAUD = 115200UL;

enum class Mode : uint8_t { ESTOP, RC_ARMED, RC_ACTIVE, AUTO_ARMED, AUTO_ACTIVE };

// Throttle (pin 10, OC1B) and steering (pin 9, OC1A) pulses are generated by
// Timer1's compare-match hardware rather than the Servo library. SoftwareSerial
// disables interrupts while sampling each XBee bit, which was delaying the
// Servo library's ISR-driven pulse edges and showing up as visible jitter on
// both channels; the compare hardware toggles the pin without needing a
// precisely-timed interrupt, so it isn't affected by that blocking.
constexpr uint16_t PWM_TICKS_PER_US = 2;   // 16MHz / 8 prescaler = 2MHz
constexpr uint16_t PWM_PERIOD_US = 20000;  // 50Hz
constexpr uint16_t PWM_PERIOD_TICKS = PWM_TICKS_PER_US * PWM_PERIOD_US;

uint16_t PulseUsToTicks(uint16_t pulse_us) {
  return pulse_us * PWM_TICKS_PER_US;
}

// Tachometer input (pin 8, PB0/PCINT0).
//
// The Traxxas RPM sensor is a hall switch watching a trigger magnet in the spur
// gear, so it produces one pulse - two edges - per spur revolution.
//
// This deliberately does NOT install an interrupt handler.  SoftwareSerial
// keeps interrupts disabled for a full byte time (~174us at 57600 baud) and
// services the bytes of an XBee frame back to back, so any ISR can be starved
// for milliseconds at a stretch; edges arriving in that window would be lost
// outright.  Instead the pin's PCINT mask bit is set while its group interrupt
// enable (PCIE0) is left clear.  The hardware still latches PCIF0 on every
// edge, and a flag set by hardware is unaffected by cli() - it simply waits
// until the main loop reads it.
//
// The cost is that PCIF0 is a single bit, so one poll observes "at least one
// edge" rather than a count.  Reading the pin level alongside the flag recovers
// most of that: a changed level is one edge, an unchanged level is both edges
// of a pulse that fit inside one loop stall.  Measured on the bench the hall
// pulse is only ~10% of a revolution (~2ms at 3000 spur RPM), shorter than a
// blocking XBee transmit, and roughly 5% of revolutions arrived merged that
// way.  Counting them keeps the revolution count exact; only that one
// revolution's timestamp is late, by at most the stall.
//
// PIN CHOICE: pin 5 is the natural candidate (it is broken out on the shield,
// and it is T1, the hardware counter input) but it does not work here.  T1 is
// Timer1's external clock source and Timer1 is fully committed to the servo
// PWM above (ICR1 as TOP, OCR1A/OCR1B as the two compare outputs).  Pin 5 also
// sits in PORTD, whose PCINT2 group belongs to SoftwareSerial's receive
// vector: adding a mask bit there would run the SoftwareSerial ISR on every
// tach edge, and that ISR clears PCIF2 before the main loop could ever see it.
// PORTB's group is unused, so pin 8 gets a latch of its own.
constexpr uint8_t TACH_PCINT_BIT = PCINT0;
// Revolution timestamps kept for the speed estimate.  Must be a power of two.
constexpr uint8_t TACH_HISTORY = 8;
// The estimate averages the whole revolutions that fit inside this span.  Wider
// is smoother but lags a speed change by about half the span.  One magnet gives
// only ~25 timestamps a second at 1500 spur RPM, so at path following speeds
// this is usually a single revolution anyway.
constexpr uint32_t TACH_WINDOW_US = 100000UL;
// No revolution for this long reads as stopped.  This is also the slowest speed
// the controller can see: 60s / 0.4s = 150 spur RPM, about 0.3 m/s.
constexpr uint32_t TACH_STALL_US = 400000UL;
// A revolution shorter than this is noise, not rotation: 3ms is 20000 spur RPM,
// well past the ~12000 a stock Slash reaches flat out.
constexpr uint32_t TACH_MIN_PERIOD_US = 3000UL;
// Trigger magnets installed in the spur gear.
constexpr uint8_t TACH_PULSES_PER_REV = 1;

// Battery monitor (A0).
//
// Divider is 100k (pack) / 9.09k (ground), both 1%, with 100nF across the
// bottom leg.  Ratio 9.09/109.09 = 0.083325 and a 8.3k Thevenin source
// impedance, just inside the ADC's 10k guideline.
//
// The reference is the internal 1.1V bandgap rather than AVCC.  AVCC is the
// board's 5V rail, which moves several percent with USB and regulator load;
// referred back through the divider that is hundreds of millivolts of error at
// the pack.  The bandgap is only specified to 1.0-1.2V but it is stable, so a
// one-time calibration removes the offset.
//
// 1.1V / 1024 counts = 1.0742mV per count at the pin, / 0.083325 = 12.89mV per
// count at the pack.  CALIBRATION: read a known pack voltage with a meter,
// compare against the reported millivolts, and scale this constant by
// (meter / reported).
//
// Calibrated 2026-09-12: meter 12.31V against 12.63V reported, so
// 12890 * (12310 / 12630) = 12563.  That implies an effective bandgap of
// 1.1V * 0.9746 = 1.072V, inside the datasheet's 1.0-1.2V spread, so the
// correction is the reference tolerance and not a divider fault.
constexpr uint32_t BATTERY_UV_PER_COUNT = 12563UL;
constexpr uint8_t BATTERY_ADC_CHANNEL = 0;
// Averaging 64 conversions recovers roughly three bits, which puts the
// quantization well below what the 8-bit BATTERY_LEVEL field can carry.
constexpr uint8_t BATTERY_OVERSAMPLE = 64;
// The bandgap needs time to settle after being selected as the reference; the
// first few conversions after startup read low.
constexpr uint8_t BATTERY_WARMUP_SAMPLES = 8;
// Exponential filter over the averaged blocks.  A block is 64 * 104us = 6.7ms,
// so shifting by 7 (N = 128) gives roughly a 0.85s time constant - slow enough
// to ride through throttle sag instead of reporting it as a discharged pack.
constexpr uint8_t BATTERY_FILTER_SHIFT = 7;
// Endpoints of the reported 0-255 scale.  3S lithium polymer: 4.2V per cell
// charged, and a 3.33V per cell floor.
constexpr uint16_t BATTERY_EMPTY_MV = 10000;
constexpr uint16_t BATTERY_FULL_MV = 12600;

void CopyRejectedJetsonFrame(const uint8_t* source,
                             uint8_t sourceLength,
                             uint8_t* destination,
                             uint8_t& destinationLength) {
  destinationLength = min(sourceLength, REJECTED_FRAME_CAPTURE);
  for (uint8_t index = 0; index < destinationLength; ++index) {
    destination[index] = source[index];
  }
}

void EncodeHex(const uint8_t* source, uint8_t sourceLength, char* destination) {
  constexpr char kHex[] = "0123456789ABCDEF";
  for (uint8_t index = 0; index < sourceLength; ++index) {
    destination[index * 2] = kHex[source[index] >> 4];
    destination[index * 2 + 1] = kHex[source[index] & 0x0F];
  }
  destination[sourceLength * 2] = '\0';
}

// Packing helpers for the binary offboard messages

bool UnpackBit(uint8_t field, uint8_t bit) {
  return (field & (1U << bit)) != 0;
}

void PackBit(uint8_t& field, uint8_t bit, bool value) {
  if (value) {
    field |= (1U << bit);
  }
}

// Little endian, matching the AVR's native byte order and Python's '<H'.
void PackUint16(uint8_t* buffer, uint16_t value) {
  buffer[0] = static_cast<uint8_t>(value & 0xFF);
  buffer[1] = static_cast<uint8_t>(value >> 8);
}

// Parsing helpers for the fixed width ASCII Jetson frames

// Exactly `width` decimal digits.  Every Jetson frame is fixed width, so a
// dropped or duplicated byte anywhere moves a delimiter or a sign onto a digit
// position and fails here or in the caller, rather than shifting a value.
bool ParseDigits(const uint8_t* data, uint8_t width, uint32_t& value) {
  value = 0;
  for (uint8_t index = 0; index < width; ++index) {
    if (data[index] < '0' || data[index] > '9') {
      return false;
    }
    value = value * 10 + static_cast<uint32_t>(data[index] - '0');
  }
  return true;
}

// A '+' or '-' followed by exactly `width` digits.
bool ParseSigned(const uint8_t* data, uint8_t width, int32_t& value) {
  if (data[0] != '+' && data[0] != '-') {
    return false;
  }
  uint32_t magnitude = 0;
  if (!ParseDigits(data + 1, width, magnitude)) {
    return false;
  }
  value = (data[0] == '-') ? -static_cast<int32_t>(magnitude) : static_cast<int32_t>(magnitude);
  return true;
}

// Uppercase only, matching what the Jetson emits.
bool ParseHexNibble(uint8_t character, uint8_t& value) {
  if (character >= '0' && character <= '9') {
    value = character - '0';
    return true;
  }
  if (character >= 'A' && character <= 'F') {
    value = character - 'A' + 10;
    return true;
  }
  return false;
}

// Onboard and offboard messages

typedef struct {
  bool ESTOP{false};
  bool AUTO_ARM{false};
  bool MANUAL_START{false};
  bool RC_PRESENT{false};
  uint8_t AXIS_LX{127};
  uint8_t AXIS_LY{127};
  uint8_t AXIS_RX{127};
  uint8_t AXIS_RY{127};
  bool BUTTON_X{false};
  bool BUTTON_O{false};
  bool BUTTON_SQUARE{false};
  bool BUTTON_TRIANGLE{false};
  bool BUTTON_L1{false};
  bool BUTTON_R1{false};
  bool BUTTON_L2{false};
  bool BUTTON_R2{false};
  bool BUTTON_L3{false};
  bool BUTTON_R3{false};
  bool BUTTON_SELECT{false};
  bool BUTTON_START{false};
  bool BUTTON_PS{false};
  bool BUTTON_UP{false};
  bool BUTTON_RIGHT{false};
  bool BUTTON_DOWN{false};
  bool BUTTON_LEFT{false};

  // Byte 0 is the format tag.  Bytes 1-3 are packed booleans, bytes 4-7 the
  // four axes.  Exact length is required: a truncated frame must be rejected
  // rather than parsed with its missing axes left at whatever the defaults are.
  bool deSerialize(const uint8_t* data, uint8_t dataLength) {
    if (dataLength != OFFBOARD_CMD_LENGTH || data[0] != OFFBOARD_CMD_TAG) {
      return false;
    }

    const uint8_t flagsA = data[1];
    const uint8_t flagsB = data[2];
    const uint8_t flagsC = data[3];

    // Reserved bits must be zero.  This is what makes a future format revision
    // fail closed on old firmware instead of decoding into garbage flags.
    if ((flagsC & 0xE0) != 0) {
      return false;
    }

    ESTOP = UnpackBit(flagsA, 0);
    AUTO_ARM = UnpackBit(flagsA, 1);
    MANUAL_START = UnpackBit(flagsA, 2);
    RC_PRESENT = UnpackBit(flagsA, 3);
    BUTTON_X = UnpackBit(flagsA, 4);
    BUTTON_O = UnpackBit(flagsA, 5);
    BUTTON_SQUARE = UnpackBit(flagsA, 6);
    BUTTON_TRIANGLE = UnpackBit(flagsA, 7);

    BUTTON_L1 = UnpackBit(flagsB, 0);
    BUTTON_R1 = UnpackBit(flagsB, 1);
    BUTTON_L2 = UnpackBit(flagsB, 2);
    BUTTON_R2 = UnpackBit(flagsB, 3);
    BUTTON_L3 = UnpackBit(flagsB, 4);
    BUTTON_R3 = UnpackBit(flagsB, 5);
    BUTTON_SELECT = UnpackBit(flagsB, 6);
    BUTTON_START = UnpackBit(flagsB, 7);

    BUTTON_PS = UnpackBit(flagsC, 0);
    BUTTON_UP = UnpackBit(flagsC, 1);
    BUTTON_RIGHT = UnpackBit(flagsC, 2);
    BUTTON_DOWN = UnpackBit(flagsC, 3);
    BUTTON_LEFT = UnpackBit(flagsC, 4);

    AXIS_LX = data[4];
    AXIS_LY = data[5];
    AXIS_RX = data[6];
    AXIS_RY = data[7];

    return true;
  }

} FromOffboard;

typedef struct {
  Mode MODE{Mode::ESTOP};
  uint8_t BATTERY_LEVEL{0};
  uint16_t BATTERY_MV{0};
  uint16_t STEERING_OUTPUT_US{0};
  uint16_t THROTTLE_OUTPUT_US{0};
  uint16_t RPM{0};

  // Raw millivolts travel alongside the scaled 0-255 level so the offboard
  // display can show an actual pack voltage; the scaled field alone cannot be
  // inverted once the endpoints change.
  bool serialize(uint8_t* buffer, uint8_t bufferSize) {
    if (bufferSize < OFFBOARD_STATUS_LENGTH) {
      return false;
    }

    buffer[0] = OFFBOARD_STATUS_TAG;
    buffer[1] = static_cast<uint8_t>(MODE);
    buffer[2] = BATTERY_LEVEL;
    PackUint16(&buffer[3], BATTERY_MV);
    PackUint16(&buffer[5], STEERING_OUTPUT_US);
    PackUint16(&buffer[7], THROTTLE_OUTPUT_US);
    PackUint16(&buffer[9], RPM);
    return true;
  }

} ToOffboard;

// Largest target the Jetson may request, in either direction.
constexpr int16_t MAX_TARGET_RPM = 20000;

typedef struct {
  bool AUTO_READY{false};
  uint8_t CMD_STEERING{127};
  // Signed spur RPM, positive forward.  Spur RPM rather than a ground speed
  // keeps the drivetrain geometry in one place - the Jetson, which converts
  // from m/s - instead of two that could disagree.
  int16_t TARGET_RPM{0};

  bool deSerialize(const uint8_t* data, uint8_t dataLength) {
    // Always exactly "C,b,sss,+rrrrr".  The exact length check is what turns
    // a byte lost on the USB link into a rejected frame.
    if (dataLength != 14 || data[0] != 'C' || data[1] != ',' || (data[2] != '0' && data[2] != '1') || data[3] != ',' ||
        data[7] != ',') {
      return false;
    }

    uint32_t steering = 0;
    int32_t target = 0;
    if (!ParseDigits(data + 4, 3, steering) || !ParseSigned(data + 8, 5, target)) {
      return false;
    }
    if (steering > 255 || target > MAX_TARGET_RPM || target < -MAX_TARGET_RPM) {
      return false;
    }

    AUTO_READY = data[2] == '1';
    CMD_STEERING = static_cast<uint8_t>(steering);
    TARGET_RPM = static_cast<int16_t>(target);
    return true;
  }

} FromJetson;

// Always exactly "G,qqq,t," then the eight SpeedGains values in declaration
// order as "+nnnnnnn," in thousandths, then "hh": the 8-bit sum of every
// preceding byte in uppercase hex.  Unlike a drive command, which is replaced
// 50 times a second, a corrupted gain would persist, so this frame carries a
// checksum.
constexpr uint8_t GAINS_FIELDS = 8;
constexpr uint8_t GAINS_HEADER_LENGTH = 8;
constexpr uint8_t GAINS_FIELD_LENGTH = 9;
constexpr uint8_t GAINS_FRAME_LENGTH = GAINS_HEADER_LENGTH + GAINS_FIELDS * GAINS_FIELD_LENGTH + 2;

// Speed controller tuning.  The Jetson sends a set at startup and whenever its
// parameters change, so the car can be retuned under load without a reflash;
// these compiled-in values only apply until then.
//
// Output is a throttle pulse offset from neutral in microseconds and speed is
// spur RPM.  Scaling per 1000 RPM keeps the numbers readable.  Keep these in
// step with the defaults in jetson/cfr_arduino_bridge/config/arduino_bridge.yaml.
//
// TUNED ON BLOCKS, see Speed Control in the top level README.  A car on the
// ground carries several times the inertia and more drag, so expect kS/kV to
// rise and kP/kI to need retuning.
struct SpeedGains {
  float kS{28.0f};         // us, added whenever the target is nonzero
  float kV{9.5f};          // us per 1000 RPM of target
  float kP{16.0f};         // us per 1000 RPM of error
  float kI{10.0f};         // us per 1000 RPM of error, per second
  float kD{0.0f};          // us per 1000 RPM per second of measured speed change
  float iLimit{60.0f};     // us, integrator clamp
  float outLimit{128.0f};  // us, largest drive offset
  float brakeLimit{0.0f};  // us of braking past SPEED_BRAKE_THRESHOLD_US; 0 coasts
  uint8_t seq{0};          // echoed in the status frame; 0 means these defaults
  bool trace{false};       // emit a T line every control tick

  // Leaves every field untouched unless the whole frame is valid.
  bool deSerialize(const uint8_t* data, uint8_t dataLength) {
    if (dataLength != GAINS_FRAME_LENGTH || data[0] != 'G' || data[1] != ',' || data[5] != ',' ||
        (data[6] != '0' && data[6] != '1') || data[7] != ',') {
      return false;
    }

    uint8_t sum = 0;
    for (uint8_t index = 0; index < GAINS_FRAME_LENGTH - 2; ++index) {
      sum += data[index];
    }
    uint8_t high = 0;
    uint8_t low = 0;
    if (!ParseHexNibble(data[GAINS_FRAME_LENGTH - 2], high) || !ParseHexNibble(data[GAINS_FRAME_LENGTH - 1], low) ||
        sum != static_cast<uint8_t>((high << 4) | low)) {
      return false;
    }

    uint32_t sequence = 0;
    if (!ParseDigits(data + 2, 3, sequence) || sequence > 255) {
      return false;
    }

    float values[GAINS_FIELDS];
    for (uint8_t field = 0; field < GAINS_FIELDS; ++field) {
      const uint8_t offset = GAINS_HEADER_LENGTH + field * GAINS_FIELD_LENGTH;
      int32_t thousandths = 0;
      if (!ParseSigned(data + offset, 7, thousandths) || data[offset + GAINS_FIELD_LENGTH - 1] != ',') {
        return false;
      }
      values[field] = thousandths / 1000.0f;
    }

    // Limits are magnitudes, and must keep the pulse inside [1000us, 2000us].
    if (values[5] < 0.0f || values[6] < 0.0f || values[6] > 500.0f || values[7] < 0.0f || values[7] > 440.0f) {
      return false;
    }

    kS = values[0];
    kV = values[1];
    kP = values[2];
    kI = values[3];
    kD = values[4];
    iLimit = values[5];
    outLimit = values[6];
    brakeLimit = values[7];
    seq = static_cast<uint8_t>(sequence);
    trace = data[6] == '1';
    return true;
  }
};

typedef struct {
  bool ESTOP{false};
  bool AUTO_ARM{false};
  bool MANUAL_START{false};
  Mode MODE{Mode::ESTOP};
  uint8_t BATTERY_LEVEL{0};
  // Spur RPM signed by the controller's direction estimate: the tach itself
  // cannot see direction, so this is positive whenever the direction is unknown.
  int16_t RPM{0};
  // Signed spur RPM the controller is tracking right now.  Zero while it is
  // stopping the car ahead of a reversal, so it can differ from the command.
  int16_t TARGET_RPM{0};
  uint16_t THROTTLE_US{1500};
  uint8_t GAINS_SEQ{0};

  // Returns the frame length including the trailing newline, or 0 if it did
  // not fit.  Longest is "1,1,1,4,255,-20000,-20000,2000,255,\n", 36 bytes.
  uint8_t serialize(uint8_t* buffer, uint8_t bufferSize) {
    const int length = snprintf(reinterpret_cast<char*>(buffer),
                                bufferSize,
                                "%u,%u,%u,%u,%u,%d,%d,%u,%u,\n",
                                ESTOP,
                                AUTO_ARM,
                                MANUAL_START,
                                static_cast<uint8_t>(MODE),
                                BATTERY_LEVEL,
                                RPM,
                                TARGET_RPM,
                                THROTTLE_US,
                                GAINS_SEQ);
    return (length > 0 && length < bufferSize) ? static_cast<uint8_t>(length) : 0;
  }

} ToJetson;

// Helpers

bool IsTimedOut(unsigned long latestUpdate, unsigned long sampleTime, unsigned long timeout) {
  // Handle 32-bit rollover
  if (latestUpdate > sampleTime) {
    return (0xFFFFFFFFUL - latestUpdate + sampleTime) >= timeout;
  }
  return (sampleTime - latestUpdate) >= timeout;
}

bool IsNearlyCenter(uint8_t value, uint8_t centerValue = 127, uint8_t tolerance = 5) {
  if (centerValue < tolerance) {
    return value <= (centerValue + tolerance);
  } else if ((255 - centerValue) < tolerance) {
    return value >= (centerValue - tolerance);
  }
  return (value >= (centerValue - tolerance)) && (value <= (centerValue + tolerance));
}

// Sensors

struct Tachometer {
  unsigned long revolutionUs[TACH_HISTORY]{};
  uint8_t newest{0};
  uint8_t revolutions{0};  // timestamps held, saturating at TACH_HISTORY
  uint8_t level{1};        // pin level after the last edge seen
  uint16_t mergedPulses{0};
  uint16_t rejectedEdges{0};
  uint16_t rpm{0};

  void begin() {
    DDRB &= ~_BV(DDB0);  // input
    // The sensor output is open collector: it only ever pulls the line low and
    // leaves it floating otherwise, so without a pullup no edge is ever latched.
    PORTB |= _BV(PORTB0);
    PCMSK0 = _BV(TACH_PCINT_BIT);
    PCICR &= ~_BV(PCIE0);  // flag only.  Deliberately no vector - see above.
    PCIFR = _BV(PCIF0);    // write 1 to clear anything latched during boot
    level = (PINB & _BV(PINB0)) ? 1 : 0;
  }

  // Cheap enough to call every loop iteration, and worth calling again
  // immediately after anything that blocks.
  void poll() {
    if (!(PCIFR & _BV(PCIF0))) {
      return;
    }
    PCIFR = _BV(PCIF0);
    const unsigned long nowUs = micros();
    const uint8_t pin = (PINB & _BV(PINB0)) ? 1 : 0;

    // The magnet pulls the line low, so each falling edge is one revolution.
    // An unchanged level means both edges of a pulse fell inside one stall,
    // which is still exactly one revolution.
    const bool merged = pin == level;
    const bool falling = !merged && pin == 0;
    level = pin;
    if (!merged && !falling) {
      return;
    }
    if (revolutions > 0 && (nowUs - revolutionUs[newest]) < TACH_MIN_PERIOD_US) {
      ++rejectedEdges;
      return;
    }
    if (merged) {
      ++mergedPulses;
    }
    newest = (newest + 1) & (TACH_HISTORY - 1);
    revolutionUs[newest] = nowUs;
    if (revolutions < TACH_HISTORY) {
      ++revolutions;
    }
  }

  // Once per control tick.
  //
  // Timing whole revolutions, rather than counting edges inside a fixed gate,
  // is what makes this usable for control: a 200ms gate quantizes to 300 RPM
  // and lags by 100ms, while a single revolution at 1500 RPM takes 40ms.
  void update(unsigned long nowUs) {
    const unsigned long sinceUs = nowUs - revolutionUs[newest];
    if (revolutions > 0 && sinceUs >= TACH_STALL_US) {
      // Forget the history too, so the first revolution after a stop is not
      // timed against one from before it.
      revolutions = 0;
    }
    if (revolutions < 2) {
      rpm = 0;
      return;
    }

    uint8_t spanned = 1;
    while (spanned + 1 < revolutions &&
           (revolutionUs[newest] - revolutionUs[(newest - spanned - 1) & (TACH_HISTORY - 1)]) <= TACH_WINDOW_US) {
      ++spanned;
    }
    unsigned long spanUs = revolutionUs[newest] - revolutionUs[(newest - spanned) & (TACH_HISTORY - 1)];

    // A revolution still in progress that has already outlasted the measured
    // period bounds the speed from above.  Without this a wheel that stops
    // abruptly would hold its last speed until TACH_STALL_US.
    if (sinceUs > spanUs / spanned) {
      spanUs = sinceUs;
      spanned = 1;
    }

    const uint32_t estimate = (60000000UL * spanned) / (spanUs * TACH_PULSES_PER_REV);
    rpm = (estimate > 0xFFFFUL) ? 0xFFFFU : static_cast<uint16_t>(estimate);
  }
};

struct BatteryMonitor {
  uint32_t accumulator{0};
  uint8_t sampleCount{0};
  uint8_t warmup{BATTERY_WARMUP_SAMPLES};
  int32_t filteredMvQ8{0};
  bool valid{false};

  void begin() {
    // REFS1:0 = 11 selects the internal 1.1V bandgap.
    ADMUX = _BV(REFS1) | _BV(REFS0) | BATTERY_ADC_CHANNEL;
    // /128 prescaler = 125kHz, inside the 50-200kHz window the datasheet wants
    // for full 10-bit accuracy.  13 clocks per conversion = 104us, and because
    // conversions are started and collected by polling, none of that blocks.
    ADCSRA = _BV(ADEN) | _BV(ADPS2) | _BV(ADPS1) | _BV(ADPS0);
    ADCSRB = 0;
    DIDR0 = _BV(ADC0D);  // disable the digital input buffer to cut ADC noise
    ADCSRA |= _BV(ADSC);
  }

  // NOTE: this owns ADMUX/ADCSRA outright.  Calling analogRead() anywhere in
  // this sketch would reset the reference selection back to AVCC and silently
  // scale every reading by 4.5x.
  void poll() {
    if (ADCSRA & _BV(ADSC)) {
      return;  // conversion still running
    }
    const uint16_t raw = ADC;
    ADCSRA |= _BV(ADSC);  // chain the next conversion immediately

    if (warmup > 0) {
      --warmup;
      return;
    }

    accumulator += raw;
    if (++sampleCount < BATTERY_OVERSAMPLE) {
      return;
    }
    // 64 * 1023 * BATTERY_UV_PER_COUNT fits comfortably inside 32 bits.
    const uint16_t mv = static_cast<uint16_t>((accumulator * BATTERY_UV_PER_COUNT) / (1000UL * BATTERY_OVERSAMPLE));
    accumulator = 0;
    sampleCount = 0;

    const int32_t sampleQ8 = static_cast<int32_t>(mv) << 8;
    if (!valid) {
      filteredMvQ8 = sampleQ8;  // seed rather than ramping up from zero
      valid = true;
    } else {
      filteredMvQ8 += (sampleQ8 - filteredMvQ8) >> BATTERY_FILTER_SHIFT;
    }
  }

  uint16_t milliVolts() const { return static_cast<uint16_t>(filteredMvQ8 >> 8); }

  uint8_t level() const {
    if (!valid) {
      return 0;
    }
    const uint16_t mv = milliVolts();
    if (mv <= BATTERY_EMPTY_MV) {
      return 0;
    }
    if (mv >= BATTERY_FULL_MV) {
      return 255;
    }
    return static_cast<uint8_t>((static_cast<uint32_t>(mv - BATTERY_EMPTY_MV) * 255UL) /
                                (BATTERY_FULL_MV - BATTERY_EMPTY_MV));
  }
};

Tachometer tach;
BatteryMonitor battery;

struct XBeeRx16Parser {
  static const uint8_t maxFrameLength = 64;

  enum class State : uint8_t { WAIT_START, LENGTH_MSB, LENGTH_LSB, FRAME };

  State state{State::WAIT_START};
  uint8_t frameData[maxFrameLength];
  uint16_t frameLength{0};
  uint8_t frameIndex{0};
  uint8_t checksum{0};
  bool escaped{false};

  void reset() {
    state = State::WAIT_START;
    frameLength = 0;
    frameIndex = 0;
    checksum = 0;
    escaped = false;
  }

  bool readFrame(uint8_t*& payload, uint8_t& payloadLength) {
    uint8_t bytesRead = 0;
    while (serXBee.available() && bytesRead < 16) {
      uint8_t value = serXBee.read();
      ++bytesRead;

      if (state == State::WAIT_START) {
        if (value == START_BYTE) {
          state = State::LENGTH_MSB;
        }
        continue;
      }

      if (escaped) {
        value ^= 0x20;
        escaped = false;
      } else if (value == ESCAPE) {
        escaped = true;
        continue;
      } else if (value == START_BYTE) {
        reset();
        state = State::LENGTH_MSB;
        continue;
      }

      switch (state) {
        case State::LENGTH_MSB:
          frameLength = static_cast<uint16_t>(value) << 8;
          state = State::LENGTH_LSB;
          break;
        case State::LENGTH_LSB:
          frameLength |= value;
          if (frameLength == 0 || frameLength > maxFrameLength) {
            reset();
          } else {
            frameIndex = 0;
            checksum = 0;
            state = State::FRAME;
          }
          break;
        case State::FRAME:
          if (frameIndex < frameLength) {
            frameData[frameIndex++] = value;
            checksum += value;
            break;
          }

          {
            const bool valid =
                static_cast<uint8_t>(checksum + value) == 0xFF && frameData[0] == RX_16_RESPONSE && frameLength >= 5;
            if (valid) {
              payload = frameData + 5;
              payloadLength = frameLength - 5;
            }
            reset();
            if (valid) {
              return true;
            }
          }
          break;
        case State::WAIT_START:
          break;
      }
    }
    return false;
  }
};

XBeeRx16Parser xbeeRxParser;

// Caps max throttle deflection to 1/4 of full scale (25%) in both directions.
// Chosen because it evenly divides the *4 us-per-count step below, so the
// full 8-bit input resolution survives the scale-down with no rounding loss.
constexpr uint8_t THROTTLE_SCALE_DIVISOR = 4;

// Deadband around center [125,130].  Overall pulse range [1000us,2000us],
// narrowed around 1500us by scaleDivisor.
int PctToPulseLength(uint8_t throttle, bool deadband = true, uint8_t scaleDivisor = 1) {
  if (deadband) {
    if (throttle > 130) {
      return 1500 + ((throttle - 130) * 4) / scaleDivisor;
    } else if (throttle < 125) {
      return 1500 + ((throttle - 124) * 4) / scaleDivisor;
    }
    return 1500;
  } else {
    // Some saturation at min and max values
    return constrain(((static_cast<int>(throttle) - 127) * 4) / scaleDivisor + 1500, 1000, 2000);
  }
}

// Low speed throttle dithering.
//
// The VXL-3S ignores +/-50us around 1500us outright, and the slowest speed it
// will actually hold - a hair past that deadband - is already faster than path
// following wants.  The ESC's floor, not the command resolution, is what sets
// minimum speed, so no amount of finer pulse width buys anything.
//
// That deadband is expensive at the scaling this sketch uses.  THROTTLE_SCALE_
// DIVISOR makes the auto-mode map exactly 1us per count over [1373us,1628us],
// so the dead +/-50us swallows 101 of the 255 command counts - roughly 40% of
// the Jetson's authority - and leaves only ~73us of live pulse on the forward
// side.
//
// Instead the output stage time-averages.  For a request smaller than the
// smallest pulse the ESC responds to, it alternates that pulse with neutral
// frame by frame and lets the vehicle's inertia average the result.  This also
// removes the need for a separate deadband compensation: the region the ESC
// used to ignore outright is now the duty-controlled crawl region, so the
// command to motion map is monotonic all the way down to neutral.
//
// Duty comes from a first order sigma-delta rather than a divide-by-N counter
// because the error feedback spreads the active frames as evenly as a 50Hz
// frame rate allows, which keeps the ripple high frequency enough for the car
// to smooth mechanically.
//
// The averaged speed is monotonic in duty but NOT linear - the car accelerates
// on an active frame and coasts against drag on an idle one - and below some
// duty static friction wins and it does not move at all.  SpeedController
// closes the loop on the tachometer around it, which takes care of both.
constexpr uint16_t THROTTLE_NEUTRAL_US = 1500;
// Smallest offset from neutral the ESC actually responds to.  The measured
// deadband edge is 50us, and a pulse sitting exactly on that edge responds
// weakly and inconsistently, so this carries a little margin past it.
//
// MEASURE THIS: on blocks, walk the pulse up from 1500us until the wheels turn
// every time rather than sometimes.  Too low and the active frames do nothing,
// which reads as a dead zone that got wider rather than narrower; too high and
// each active frame is a bigger kick, so the crawl is coarser and lurchier than
// it needs to be.  Setting it to 0 disables dithering entirely and restores the
// previous straight-through behavior.
constexpr uint16_t THROTTLE_DITHER_ACTIVE_US = 55;
// Duty is carried as a fraction of this.  A power of two keeps the sigma-delta
// down to an add and a compare.
constexpr uint16_t THROTTLE_DITHER_SCALE = 256;
// Duty times the 50Hz frame rate is the rate at which torque pulses arrive at
// the drivetrain.  Below roughly 10Hz they stop blending into motion and read
// as lurching, so anything under this floor is dropped to neutral rather than
// hammering the gear lash for no useful speed.
constexpr uint16_t THROTTLE_DITHER_MIN_DUTY = 51;  // 20% of scale -> 10Hz
// Dithering the reverse side walks the ESC from neutral to reverse-side
// throttle tens of times a second, and the VXL-3S arbitrates brake against
// reverse on exactly that transition: after a neutral frame a reverse pulse is
// reverse drive.  From a standstill that is exactly what slow reverse needs,
// and on the bench it mirrors forward closely (1470us ~240 and 1460us ~1070
// spur RPM, against 1530us ~225 and 1540us ~1100).  It is also why
// SpeedController never brakes through the dithered range.
constexpr bool THROTTLE_DITHER_REVERSE = true;

// Owns OCR1B outright.  Nothing else may write it: a write from elsewhere in
// the main loop would land in the same double buffer and silently drop a
// dither frame.
struct ThrottleOutput {
  uint16_t idleUs{THROTTLE_NEUTRAL_US};
  uint16_t activeUs{THROTTLE_NEUTRAL_US};
  uint16_t duty{0};
  uint16_t accumulator{0};
  int8_t activeSign{0};

  void begin() {
    OCR1B = PulseUsToTicks(THROTTLE_NEUTRAL_US);
    TIFR1 = _BV(TOV1);  // write 1 to clear anything latched during boot
  }

  // Requested pulse in microseconds - exactly the value that used to be written
  // straight to OCR1B.  Cheap enough to call every loop iteration.
  void set(uint16_t pulseUs) {
    const int16_t offset = static_cast<int16_t>(pulseUs) - static_cast<int16_t>(THROTTLE_NEUTRAL_US);
    const int16_t magnitude = (offset < 0) ? -offset : offset;
    const int8_t sign = (offset < 0) ? -1 : ((offset > 0) ? 1 : 0);

    // Big enough for the ESC to act on by itself - pass it through untouched.
    if (magnitude >= static_cast<int16_t>(THROTTLE_DITHER_ACTIVE_US)) {
      setSteady(pulseUs, sign);
      return;
    }
    // Reverse side with reverse dithering off.  The ESC ignores this request
    // today, so holding neutral keeps that behavior instead of inventing a
    // lurch the caller did not ask for.
    if (sign < 0 && !THROTTLE_DITHER_REVERSE) {
      setSteady(THROTTLE_NEUTRAL_US, 0);
      return;
    }

    const uint16_t requestedDuty =
        static_cast<uint16_t>((static_cast<uint32_t>(magnitude) * THROTTLE_DITHER_SCALE) / THROTTLE_DITHER_ACTIVE_US);
    if (requestedDuty < THROTTLE_DITHER_MIN_DUTY) {
      setSteady(THROTTLE_NEUTRAL_US, 0);
      return;
    }

    if (sign != activeSign) {
      accumulator = 0;  // no carrying accumulated error across a direction change
    }
    activeSign = sign;
    idleUs = THROTTLE_NEUTRAL_US;
    activeUs = (sign > 0) ? (THROTTLE_NEUTRAL_US + THROTTLE_DITHER_ACTIVE_US) :
                            (THROTTLE_NEUTRAL_US - THROTTLE_DITHER_ACTIVE_US);
    duty = requestedDuty;
  }

  // Advances one dither frame per PWM period.  Polled from the main loop rather
  // than driven by an ISR for the same reason the tachometer is: SoftwareSerial
  // holds interrupts off for milliseconds at a stretch, but TOV1 is set by
  // hardware and simply waits.  Missing a poll repeats one frame, which nudges
  // the realized duty rather than glitching the pulse, so it degrades quietly.
  void poll() {
    if (!(TIFR1 & _BV(TOV1))) {
      return;
    }
    TIFR1 = _BV(TOV1);

    uint16_t pulseUs = idleUs;
    accumulator += duty;
    if (accumulator >= THROTTLE_DITHER_SCALE) {
      accumulator -= THROTTLE_DITHER_SCALE;
      pulseUs = activeUs;
    }
    // TOV1 is set as the counter wraps, which in fast PWM is also when the
    // compare double buffer latches, so this write takes effect on the
    // following frame - the same latency the direct OCR1B write it replaces
    // already had.
    OCR1B = PulseUsToTicks(pulseUs);
  }

 private:
  void setSteady(uint16_t pulseUs, int8_t sign) {
    if (sign != activeSign) {
      accumulator = 0;
    }
    activeSign = sign;
    idleUs = pulseUs;
    activeUs = pulseUs;
    duty = 0;  // sigma-delta never fires, so every frame emits idleUs
  }
};

ThrottleOutput throttle;

// Speed control
//
// Closes the loop from the Jetson's target spur RPM to the throttle pulse.  The
// output is a pulse offset in microseconds and goes through ThrottleOutput, so
// the dithered crawl region is simply the bottom of the actuator's range.
//
// Bench characterization, car on blocks, 11.8V pack, 2026-09-12:
//   * Nothing below ~1528us: that little dither duty cannot break static
//     friction.
//   * 1530-1555us, dithered: roughly linear at ~105 spur RPM per us, 225-2800.
//   * 1555-1585us: flat at ~2900 RPM, the ESC's own minimum steady speed.
//   * Above 1590us: ~50 RPM per us.
//   * Steps look like a first order lag with a 450-650ms time constant and
//     little dead time.  Coasting down at neutral is slower, 700-1000ms.
// kS and kV are the straight line through the dithered region.  On the ground
// the lag grows with the car's inertia; see SpeedGains.

// Once per 20ms PWM frame.  Faster would only recompute from the same tach
// timestamps, and could not change the output before the next frame anyway.
constexpr unsigned long CONTROL_PERIOD_US = 20000UL;
// A longer dt is a stalled loop rather than a control period, and would dump a
// burst into the integrator.
constexpr float CONTROL_MAX_DT_S = 0.1f;
// Stopped for this long, on top of the TACH_STALL_US it already took for the
// speed to read zero, before the direction estimate is released.
constexpr unsigned long SPEED_SETTLE_MS = 100;
// The VXL-3S treats a reverse side pulse as brake while moving forward only
// until it sees neutral; after a neutral frame the same pulse is reverse drive.
// On the bench a steady 1440us from 2800 RPM braked to a stop and held there,
// while a dithered 1470us braked and then drove off in reverse.  So braking goes
// out as a steady pulse starting this far past neutral - clear of the dither
// range - and never through the dithered path.
constexpr uint16_t SPEED_BRAKE_THRESHOLD_US = 60;
// Output below -this starts braking; output back at or above zero ends it.  The
// gap keeps an output hovering around zero from toggling the brake.
constexpr float SPEED_BRAKE_ENTER_US = 5.0f;
// Speed rising this far above the lowest seen since braking began means the ESC
// is driving in reverse instead of braking.  The tach cannot see direction, so
// left alone the controller would read that as forward speed and brake -
// reverse - harder.  Braking is locked out until the wheels settle.
constexpr uint16_t SPEED_BRAKE_RUNAWAY_RPM = 300;

struct SpeedController {
  // +1 forward, -1 reverse, 0 unknown.  The tach has no direction, so this is
  // the direction last driven, and it only changes once the wheels are stopped.
  int8_t direction{0};
  float integral{0.0f};
  uint16_t lastRpm{0};
  unsigned long lastMovingMs{0};
  bool braking{false};
  bool brakeLockout{false};
  uint16_t brakeLowRpm{0};
  // From the most recent update, for the status frame and trace.
  int16_t trackedRpm{0};
  float feedForward{0.0f};
  float proportional{0.0f};
  float derivative{0.0f};
  float output{0.0f};

  void reset() { *this = SpeedController(); }

  // Returns the throttle pulse in microseconds.
  uint16_t update(int16_t targetRpm, uint16_t measuredRpm, float dt, unsigned long nowMs, const SpeedGains& gains) {
    dt = constrain(dt, 0.0f, CONTROL_MAX_DT_S);
    const bool moving = measuredRpm > 0;
    if (moving) {
      lastMovingMs = nowMs;
    }
    const bool settled = !moving && (nowMs - lastMovingMs) >= SPEED_SETTLE_MS;
    const int8_t targetSign = (targetRpm > 0) ? 1 : ((targetRpm < 0) ? -1 : 0);

    // A reversal is tracked as a zero target until the wheels settle, so the
    // old direction coasts or brakes down before the new one is driven.
    if (targetSign != direction && (direction == 0 || settled)) {
      direction = targetSign;
      integral = 0.0f;
    }
    if (settled) {
      braking = false;
      brakeLockout = false;
    }

    const uint16_t magnitude =
        (targetSign != 0 && targetSign == direction) ? static_cast<uint16_t>(abs(static_cast<int>(targetRpm))) : 0;
    const float error = static_cast<float>(magnitude) - static_cast<float>(measuredRpm);
    trackedRpm = direction * static_cast<int16_t>(magnitude);

    feedForward = (magnitude > 0) ? gains.kS + gains.kV * magnitude / 1000.0f : 0.0f;
    proportional = gains.kP * error / 1000.0f;
    // On measurement rather than error, so a target step does not kick.
    derivative = (dt > 0.0f) ? -gains.kD * (static_cast<float>(measuredRpm) - lastRpm) / (dt * 1000.0f) : 0.0f;
    lastRpm = measuredRpm;

    // Only forward motion brakes.  In reverse the far side of neutral is
    // forward drive, which the runaway argument above makes just as unsafe, so
    // reverse only ever coasts down.
    const bool canBrake = direction > 0 && moving && gains.brakeLimit > 0.0f && !brakeLockout;
    const float upper = (magnitude > 0) ? gains.outLimit : 0.0f;
    const float lower = canBrake ? -gains.brakeLimit : 0.0f;

    if (magnitude == 0) {
      integral = 0.0f;
    } else {
      // Conditional integration: hold the integrator while the output is
      // pinned against the limit the error is pushing it toward.
      const float candidate = constrain(integral + gains.kI * error * dt / 1000.0f, -gains.iLimit, gains.iLimit);
      const float unclamped = feedForward + proportional + candidate + derivative;
      if (!(unclamped > upper && error > 0.0f) && !(unclamped < lower && error < 0.0f)) {
        integral = candidate;
      }
    }

    output = constrain(feedForward + proportional + integral + derivative, lower, upper);

    if (canBrake && (braking || output < -SPEED_BRAKE_ENTER_US)) {
      if (!braking) {
        braking = true;
        brakeLowRpm = measuredRpm;
      }
      brakeLowRpm = min(brakeLowRpm, measuredRpm);
      if (output >= 0.0f) {
        braking = false;
      } else if (measuredRpm > brakeLowRpm + SPEED_BRAKE_RUNAWAY_RPM) {
        braking = false;
        brakeLockout = true;
      }
    } else {
      braking = false;
    }

    if (braking) {
      const float effort = min(-output, gains.brakeLimit);
      return THROTTLE_NEUTRAL_US - SPEED_BRAKE_THRESHOLD_US - static_cast<uint16_t>(effort + 0.5f);
    }
    const uint16_t drive = static_cast<uint16_t>(max(output, 0.0f) + 0.5f);
    return (direction < 0) ? THROTTLE_NEUTRAL_US - drive : THROTTLE_NEUTRAL_US + drive;
  }
};

SpeedGains speedGains;
SpeedController speedController;

// Main Code

void setup() {
  xbee = XBee();

  // Setup USB serial
  Serial.begin(ONBOARD_BAUD);
  while (!Serial) {
    ;  // wait for serial port to connect
  }
  Serial.setTimeout(1);

  serXBee.begin(57600);
  while (!serXBee) {
    ;  // wait for serial port to connect
  }
  xbee.setSerial(serXBee);
  tx16.setFrameId(NO_RESPONSE_FRAME_ID);

  // Throttle to FL(10, OC1B), Steering to RL(9, OC1A)
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  // Fast PWM, TOP=ICR1 (mode 14), non-inverting on OC1A/OC1B, prescaler /8
  TCCR1A = _BV(COM1A1) | _BV(COM1B1) | _BV(WGM11);
  TCCR1B = _BV(WGM13) | _BV(WGM12) | _BV(CS11);
  ICR1 = PWM_PERIOD_TICKS - 1;
  OCR1A = PulseUsToTicks(1500);  // steering, centered

  throttle.begin();  // owns OCR1B, and centers it
  tach.begin();
  battery.begin();
}

void loop() {
  static FromOffboard offboardState;
  static FromJetson jetsonState;
  static unsigned long latestOffboardUpdate = 0;
  static unsigned long latestJetsonUpdate = 0;
  static bool offboardTimedOut = true;
  static bool jetsonTimedOut = true;
  static Mode autoMode = Mode::ESTOP;

  const auto now = millis();
  static auto lastXBeeTx = now;
  static auto lastOnboardTx = now;
  static uint16_t xbeeFrames = 0;
  static uint16_t xbeeRx16Frames = 0;
  static uint16_t xbeeValidMessages = 0;
  static uint16_t xbeeInvalidMessages = 0;
  static uint16_t validJetsonFrames = 0;
  static uint16_t invalidJetsonFrames = 0;
  static uint8_t lastRejectedJetsonFrame[REJECTED_FRAME_CAPTURE] = {};
  static uint8_t lastRejectedJetsonFrameLength = 0;
  bool receivedOffboardMessage = false;

  // Sensors.  Both are polled rather than interrupt driven, so they cost a few
  // register reads here and nothing anywhere else.
  tach.poll();
  battery.poll();
  // Polled here as well as after the command is computed below, so a PWM frame
  // that elapses during the blocking transmits at the end of the previous
  // iteration still advances the dither on schedule.
  throttle.poll();

  // Offboard Rx
  uint8_t* offboardPayload = nullptr;
  uint8_t offboardPayloadLength = 0;
  if (xbeeRxParser.readFrame(offboardPayload, offboardPayloadLength)) {
    ++xbeeFrames;
    ++xbeeRx16Frames;
    if (offboardState.deSerialize(offboardPayload, offboardPayloadLength)) {
      ++xbeeValidMessages;
      latestOffboardUpdate = now;
      receivedOffboardMessage = true;
    } else {
      ++xbeeInvalidMessages;
    }
  }

  // Onboard Rx.  Serial.readBytesUntil() returns a partial buffer when its
  // timeout expires.  Those fragments can still look like a valid three-field
  // command (for example "1,127,0" from a frame whose last digits have not
  // arrived), which turns USB packet timing into actuator noise.  Only parse
  // complete newline-terminated frames.
  static uint8_t onboardRxLength = 0;
  static bool onboardRxDiscarding = false;
  while (Serial.available() > 0) {
    const int received = Serial.read();
    if (received == '\r') {
      continue;
    }
    if (received == '\n') {
      if (!onboardRxDiscarding && onboardRxLength > 0) {
        // Decode into a candidate first.  A malformed frame must not mutate
        // the command that remains live until the USB watchdog expires.
        FromJetson candidate;
        if (candidate.deSerialize(onboardRxPayload, onboardRxLength)) {
          jetsonState = candidate;
          latestJetsonUpdate = now;
          ++validJetsonFrames;
        } else if (speedGains.deSerialize(onboardRxPayload, onboardRxLength)) {
          // Deliberately does not feed the watchdog: only a drive command
          // shows the autonomy stack is alive.
          ++validJetsonFrames;
        } else {
          ++invalidJetsonFrames;
          CopyRejectedJetsonFrame(
              onboardRxPayload, onboardRxLength, lastRejectedJetsonFrame, lastRejectedJetsonFrameLength);
        }
      } else if (onboardRxLength > 0) {
        ++invalidJetsonFrames;
        CopyRejectedJetsonFrame(
            onboardRxPayload, onboardRxLength, lastRejectedJetsonFrame, lastRejectedJetsonFrameLength);
      }
      onboardRxLength = 0;
      onboardRxDiscarding = false;
      continue;
    }
    if (onboardRxDiscarding) {
      continue;
    }
    if (onboardRxLength < sizeof(onboardRxPayload)) {
      onboardRxPayload[onboardRxLength++] = static_cast<uint8_t>(received);
    } else {
      // Drop the whole oversized frame rather than parsing its suffix as a
      // new command on the next loop iteration.
      onboardRxLength = 0;
      onboardRxDiscarding = true;
      ++invalidJetsonFrames;
      CopyRejectedJetsonFrame(
          onboardRxPayload, sizeof(onboardRxPayload), lastRejectedJetsonFrame, lastRejectedJetsonFrameLength);
    }
  }

  if (IsTimedOut(latestOffboardUpdate, now, commsTimeout_ms)) {
    offboardState = FromOffboard();
    if (!offboardTimedOut) {
      serXBee.stopListening();
      serXBee.listen();
      xbeeRxParser.reset();
    }
    offboardTimedOut = true;
  } else {
    offboardTimedOut = false;
  }

  if (IsTimedOut(latestJetsonUpdate, now, commsTimeout_ms)) {
    jetsonState = FromJetson();
    jetsonTimedOut = true;
  } else {
    jetsonTimedOut = false;
  }

  // State management
  if (offboardState.ESTOP || offboardTimedOut) {
    autoMode = Mode::ESTOP;
  } else if (offboardState.AUTO_ARM == false && autoMode != Mode::RC_ACTIVE) {
    autoMode = Mode::RC_ARMED;
  } else if (offboardState.AUTO_ARM && autoMode != Mode::AUTO_ACTIVE) {
    autoMode = Mode::AUTO_ARMED;
  }

  switch (autoMode) {
    case Mode::ESTOP:
      break;
    case Mode::RC_ARMED:
      if (offboardState.RC_PRESENT && IsNearlyCenter(offboardState.AXIS_LY) && IsNearlyCenter(offboardState.AXIS_LX)) {
        autoMode = Mode::RC_ACTIVE;
      }
      break;
    case Mode::RC_ACTIVE:
      break;
    case Mode::AUTO_ARMED:
      if (jetsonState.AUTO_READY && IsNearlyCenter(jetsonState.CMD_STEERING) && jetsonState.TARGET_RPM == 0) {
        autoMode = Mode::AUTO_ACTIVE;
      }
      break;
    case Mode::AUTO_ACTIVE:
      // AUTO_READY is an enable, not only an entry-handshake signal.  Leaving
      // AUTO_ACTIVE as soon as the Jetson clears it guarantees neutral PWM
      // between path goals while the serial link remains healthy.
      if (jetsonTimedOut || !jetsonState.AUTO_READY) {
        autoMode = Mode::AUTO_ARMED;
      }
      break;
  }

  // Speed estimate and control, once per PWM frame.  The controller only runs
  // in AUTO_ACTIVE and starts from a clean state each time it is entered, so
  // nothing integrated before an E-Stop survives it.
  static unsigned long lastControlUs = micros();
  static uint16_t speedPulseUs = THROTTLE_NEUTRAL_US;
  const unsigned long nowUs = micros();
  const bool controlTick = (nowUs - lastControlUs) >= CONTROL_PERIOD_US;
  if (controlTick) {
    const float dt = (nowUs - lastControlUs) / 1.0e6f;
    lastControlUs = nowUs;
    tach.update(nowUs);
    if (autoMode == Mode::AUTO_ACTIVE) {
      speedPulseUs = speedController.update(jetsonState.TARGET_RPM, tach.rpm, dt, now, speedGains);
    } else {
      speedController.reset();
      speedPulseUs = THROTTLE_NEUTRAL_US;
    }
  }

  // Car control
  auto throttleCmd = PctToPulseLength(127);
  auto steeringCmd = PctToPulseLength(127);

  switch (autoMode) {
    case Mode::RC_ACTIVE:
      throttleCmd = PctToPulseLength(255 - offboardState.AXIS_LY, true, THROTTLE_SCALE_DIVISOR);
      steeringCmd = PctToPulseLength(offboardState.AXIS_RX);
      break;
    case Mode::AUTO_ACTIVE:
      throttleCmd = speedPulseUs;
      // Convention is positive left for right hand rule
      steeringCmd = PctToPulseLength(255 - jetsonState.CMD_STEERING, false);
      break;
    default:
      throttleCmd = PctToPulseLength(127);
      steeringCmd = PctToPulseLength(127);
  }

  throttle.set(throttleCmd);
  throttle.poll();
  OCR1A = PulseUsToTicks(steeringCmd);

  if (controlTick && speedGains.trace) {
    // Tuning trace, one line per control tick: time, tracked and measured RPM,
    // then feedforward, proportional, integral, derivative and total output in
    // tenths of a microsecond, the requested pulse, braking, and dither duty.
    char trace[96];
    const int traceLength = snprintf(trace,
                                     sizeof(trace),
                                     "T,%lu,%d,%u,%d,%d,%d,%d,%d,%u,%u,%u\n",
                                     now,
                                     speedController.trackedRpm,
                                     tach.rpm,
                                     static_cast<int>(speedController.feedForward * 10.0f),
                                     static_cast<int>(speedController.proportional * 10.0f),
                                     static_cast<int>(speedController.integral * 10.0f),
                                     static_cast<int>(speedController.derivative * 10.0f),
                                     static_cast<int>(speedController.output * 10.0f),
                                     throttleCmd,
                                     speedController.braking,
                                     throttle.duty);
    if (traceLength > 0 && traceLength < static_cast<int>(sizeof(trace))) {
      Serial.write(trace, static_cast<size_t>(traceLength));
    }
  }

  const uint8_t batteryLevel = battery.level();

  ToOffboard offboardFeedback;
  offboardFeedback.MODE = autoMode;
  offboardFeedback.BATTERY_LEVEL = batteryLevel;
  offboardFeedback.BATTERY_MV = battery.milliVolts();
  offboardFeedback.STEERING_OUTPUT_US = steeringCmd;
  offboardFeedback.THROTTLE_OUTPUT_US = throttleCmd;
  offboardFeedback.RPM = tach.rpm;
  offboardFeedback.serialize((uint8_t*)offboardTxPayload, sizeof(offboardTxPayload));

  // Transmit immediately after a valid offboard frame. SoftwareSerial disables
  // receive interrupts while transmitting, so this avoids colliding with the
  // next 20 Hz command frame.
  if (receivedOffboardMessage && now - lastXBeeTx >= 50) {
    // Offboard Tx
    // tx16.setAddress16(rx16.getRemoteAddress16());
    tx16.setAddress16(0);
    // Fixed length: a binary payload can legitimately contain '\n', so scanning
    // for a terminator the way the Jetson frame does would truncate it.
    tx16.setPayload(offboardTxPayload, OFFBOARD_STATUS_LENGTH);
    if (enableOffboardTx) {
      xbee.send(tx16);
    }
    lastXBeeTx = now;
    // send() busy-waits with interrupts off for the whole frame.  PCIF0 held any
    // edge that arrived during it; collect it now so the timestamp is as close
    // to the edge as this architecture allows.  TOV1 was latched through it the
    // same way, so a PWM frame that elapsed during the send is not lost.
    tach.poll();
    throttle.poll();
  }

  if (now - lastOnboardTx >= 50) {
    const int16_t rpm = static_cast<int16_t>(min(tach.rpm, static_cast<uint16_t>(MAX_TARGET_RPM)));
    ToJetson onboardFeedback;
    onboardFeedback.ESTOP = offboardState.ESTOP;
    onboardFeedback.AUTO_ARM = offboardState.AUTO_ARM;
    onboardFeedback.MANUAL_START = offboardState.MANUAL_START;
    onboardFeedback.MODE = autoMode;
    onboardFeedback.BATTERY_LEVEL = batteryLevel;
    onboardFeedback.RPM = (speedController.direction < 0) ? -rpm : rpm;
    onboardFeedback.TARGET_RPM = speedController.trackedRpm;
    onboardFeedback.THROTTLE_US = throttleCmd;
    onboardFeedback.GAINS_SEQ = speedGains.seq;
    const uint8_t feedbackLength = onboardFeedback.serialize(onboardTxPayload, sizeof(onboardTxPayload));
    if (feedbackLength > 0) {
      Serial.write(onboardTxPayload, feedbackLength);
    }
    if (enableOnboardDebug) {
      char rejectedHex[sizeof(lastRejectedJetsonFrame) * 2 + 1] = {};
      EncodeHex(lastRejectedJetsonFrame, lastRejectedJetsonFrameLength, rejectedHex);
      // This uses a distinct prefix so it cannot be mistaken for the normal
      // five-field status frame consumed by the Jetson bridge.
      const int debugLength = snprintf(reinterpret_cast<char*>(onboardDebugPayload),
                                       sizeof(onboardDebugPayload),
                                       // Dither duty follows the rejected
                                       // frame, out of THROTTLE_DITHER_SCALE,
                                       // and reads 0 whenever the pulse is
                                       // going out steady.  throttleCmd remains
                                       // the requested pulse, not the dithered
                                       // one.  Last come the applied gains
                                       // sequence and the tach's merged pulse
                                       // and rejected edge counts.
                                       "D,%lu,%u,%u,%u,%u,%d,%u,%u,%u,%u,%u,%u,%s,%u,%u,%u,%u\n",
                                       now,
                                       validJetsonFrames,
                                       invalidJetsonFrames,
                                       jetsonState.AUTO_READY,
                                       jetsonState.CMD_STEERING,
                                       jetsonState.TARGET_RPM,
                                       static_cast<uint8_t>(autoMode),
                                       steeringCmd,
                                       throttleCmd,
                                       tach.rpm,
                                       battery.milliVolts(),
                                       lastRejectedJetsonFrameLength,
                                       rejectedHex,
                                       throttle.duty,
                                       speedGains.seq,
                                       tach.mergedPulses,
                                       tach.rejectedEdges);
      if (debugLength > 0 && debugLength < static_cast<int>(sizeof(onboardDebugPayload))) {
        Serial.write(onboardDebugPayload, static_cast<size_t>(debugLength));
      }
    }
    lastOnboardTx = now;
  }
}
