#include <SoftwareSerial.h>

#include <XBee.h>

XBee xbee;
SoftwareSerial serXBee(2, 3);
Tx16Request tx16 = Tx16Request();
uint8_t offboardTxPayload[18] = {};
uint8_t onboardRxPayload[16] = {};
uint8_t onboardTxPayload[14] = {};
uint8_t onboardDebugPayload[112] = {};

const unsigned long commsTimeout_ms = 200;
const bool enableOffboardTx = true;
const bool enableOnboardDebug = true;

enum class Mode : uint8_t { ESTOP, RC_ARMED, RC_ACTIVE, AUTO_ARMED, AUTO_ACTIVE };

// Throttle (pin 10, OC1B) and steering (pin 9, OC1A) pulses are generated by
// Timer1's compare-match hardware rather than the Servo library. SoftwareSerial
// disables interrupts while sampling each XBee bit, which was delaying the
// Servo library's ISR-driven pulse edges and showing up as visible jitter on
// both channels; the compare hardware toggles the pin without needing a
// precisely-timed interrupt, so it isn't affected by that blocking.
constexpr uint16_t PWM_TICKS_PER_US = 2;   // 16MHz / 8 prescaler = 2MHz
constexpr uint16_t PWM_PERIOD_US = 20000;  // 50Hz
constexpr uint16_t PWM_PERIOD_TICKS = PWM_TICKS_PER_US * PWM_PERIOD_US;

uint16_t PulseUsToTicks(uint16_t pulse_us) {
  return pulse_us * PWM_TICKS_PER_US;
}

void CopyRejectedJetsonFrame(const uint8_t* source,
                             uint8_t sourceLength,
                             uint8_t* destination,
                             uint8_t& destinationLength) {
  destinationLength = min(sourceLength, static_cast<uint8_t>(sizeof(onboardRxPayload)));
  for (uint8_t index = 0; index < destinationLength; ++index) {
    destination[index] = source[index];
  }
}

void EncodeHex(const uint8_t* source, uint8_t sourceLength, char* destination) {
  constexpr char kHex[] = "0123456789ABCDEF";
  for (uint8_t index = 0; index < sourceLength; ++index) {
    destination[index * 2] = kHex[source[index] >> 4];
    destination[index * 2 + 1] = kHex[source[index] & 0x0F];
  }
  destination[sourceLength * 2] = '\0';
}

// Serialization helpers for comma-delimited ascii messages

bool deserialize(bool& val, const uint8_t*& data, const uint8_t* end) {
  if (data == end) {
    return true;
  }

  bool error = false;
  switch (*data) {
    case '0':
      val = false;
      break;
    case '1':
      val = true;
      break;
    default:
      error = true;
  }
  while (data != end && *data != '\n' && *data != ',') {
    ++data;
  }
  if (data != end && *data == ',') {
    ++data;
  }
  return error;
}

bool deserialize(uint8_t& val, const uint8_t*& data, const uint8_t* end) {
  if (data == end || *data == '\n' || *data == ',') {
    return true;
  }

  uint32_t tempVal = 0;
  bool error = false;
  while (data != end && *data != '\n' && *data != ',') {
    switch (*data) {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        tempVal = tempVal * 10 + (*data - '0');
        break;
      default:
        error = true;
    }
    ++data;
  }
  if (tempVal > 255) {
    error = true;
    val = 0;
  } else {
    val = static_cast<uint8_t>(tempVal);
  }
  if (data != end && *data == ',') {
    ++data;
  }
  return error;
}

bool deserialize(Mode& val, const uint8_t*& data, const uint8_t* end) {
  uint8_t intMode;
  bool retVal = deserialize(intMode, data, end);
  val = static_cast<Mode>(intMode);
  return retVal;
}

bool serialize(const uint8_t& val, uint8_t** buffer) {
  uint8_t digits = 1;
  uint8_t tempVal = val;
  if (val >= 100) {
    digits = 3;
  } else if (val >= 10) {
    digits = 2;
  }
  while (digits > 0) {
    --digits;
    uint8_t digitMultiplier;
    switch (digits) {
      case 0:
        digitMultiplier = 1;
        break;
      case 1:
        digitMultiplier = 10;
        break;
      case 2:
        digitMultiplier = 100;
        break;
    }
    uint8_t newDigit = (tempVal - (tempVal % digitMultiplier)) / digitMultiplier;
    tempVal -= (newDigit * digitMultiplier);
    **buffer = '0' + newDigit;
    ++(*buffer);
  }
  **buffer = ',';
  ++(*buffer);
  return true;
}

bool serialize(const uint16_t& val, uint8_t** buffer) {
  uint16_t divisor = 1;
  while (divisor <= val / 10) {
    divisor *= 10;
  }
  while (divisor > 0) {
    **buffer = '0' + (val / divisor) % 10;
    ++(*buffer);
    divisor /= 10;
  }
  **buffer = ',';
  ++(*buffer);
  return true;
}

bool serialize(Mode& val, uint8_t** buffer) {
  uint8_t intMode = static_cast<uint8_t>(val);
  return serialize(intMode, buffer);
}

bool serialize(bool& val, uint8_t** buffer) {
  **buffer = val ? '1' : '0';
  ++(*buffer);
  **buffer = ',';
  ++(*buffer);
  return true;
}

// Onboard and offboard messages

typedef struct {
  bool ESTOP{false};
  bool AUTO_ARM{false};
  bool MANUAL_START{false};
  bool RC_PRESENT{false};
  uint8_t AXIS_LX{127};
  uint8_t AXIS_LY{127};
  uint8_t AXIS_RX{127};
  uint8_t AXIS_RY{127};
  bool BUTTON_X{false};
  bool BUTTON_O{false};
  bool BUTTON_SQUARE{false};
  bool BUTTON_TRIANGLE{false};
  bool BUTTON_L1{false};
  bool BUTTON_R1{false};
  bool BUTTON_L2{false};
  bool BUTTON_R2{false};
  bool BUTTON_L3{false};
  bool BUTTON_R3{false};
  bool BUTTON_SELECT{false};
  bool BUTTON_START{false};
  bool BUTTON_PS{false};
  bool BUTTON_UP{false};
  bool BUTTON_RIGHT{false};
  bool BUTTON_DOWN{false};
  bool BUTTON_LEFT{false};

  bool deSerialize(uint8_t* data, uint8_t dataLength) {
    bool error = false;

    // Variable length, but must have at least one character per field including
    // comma delimiters and integer fields can be no longer than 3 characters
    // each.  Optional trailing comma delimiter.
    if (dataLength < 49 || dataLength > 58) {
      return false;
    }

    const uint8_t* cursor = data;
    const uint8_t* end = data + dataLength;

    error = deserialize(ESTOP, cursor, end) || error;
    error = deserialize(AUTO_ARM, cursor, end) || error;
    error = deserialize(MANUAL_START, cursor, end) || error;
    error = deserialize(RC_PRESENT, cursor, end) || error;
    error = deserialize(AXIS_LX, cursor, end) || error;
    error = deserialize(AXIS_LY, cursor, end) || error;
    error = deserialize(AXIS_RX, cursor, end) || error;
    error = deserialize(AXIS_RY, cursor, end) || error;
    error = deserialize(BUTTON_X, cursor, end) || error;
    error = deserialize(BUTTON_O, cursor, end) || error;
    error = deserialize(BUTTON_SQUARE, cursor, end) || error;
    error = deserialize(BUTTON_TRIANGLE, cursor, end) || error;
    error = deserialize(BUTTON_L1, cursor, end) || error;
    error = deserialize(BUTTON_R1, cursor, end) || error;
    error = deserialize(BUTTON_L2, cursor, end) || error;
    error = deserialize(BUTTON_R2, cursor, end) || error;
    error = deserialize(BUTTON_L3, cursor, end) || error;
    error = deserialize(BUTTON_R3, cursor, end) || error;
    error = deserialize(BUTTON_SELECT, cursor, end) || error;
    error = deserialize(BUTTON_START, cursor, end) || error;
    error = deserialize(BUTTON_PS, cursor, end) || error;
    error = deserialize(BUTTON_UP, cursor, end) || error;
    error = deserialize(BUTTON_RIGHT, cursor, end) || error;
    error = deserialize(BUTTON_DOWN, cursor, end) || error;
    error = deserialize(BUTTON_LEFT, cursor, end) || error;

    return !error;
  }

} FromOffboard;

typedef struct {
  Mode MODE{Mode::ESTOP};
  uint8_t BATTERY_LEVEL{255};
  uint16_t STEERING_OUTPUT_US{0};
  uint16_t THROTTLE_OUTPUT_US{0};

  bool serialize(uint8_t* buffer, uint8_t bufferSize) {
    // Need enough space for max size values with comma delimiter and trailing
    // '\n' and '\0'
    if (bufferSize < 18) {
      return false;
    }

    ::serialize(MODE, &buffer);
    ::serialize(BATTERY_LEVEL, &buffer);
    ::serialize(STEERING_OUTPUT_US, &buffer);
    ::serialize(THROTTLE_OUTPUT_US, &buffer);
    *buffer = '\n';
    ++(buffer);
    *buffer = '\0';
    ++(buffer);
    return true;
  }

} ToOffboard;

typedef struct {
  bool AUTO_READY{false};
  uint8_t CMD_STEERING{127};
  uint8_t CMD_THROTTLE{127};

  bool deSerialize(const uint8_t* data, uint8_t dataLength) {
    // Jetson Serialize() always emits exactly "b,nnn,nnn\\n".  Requiring
    // the nine-byte payload before its newline prevents a damaged complete
    // line from being interpreted as a shortened but valid command.
    if (dataLength != 9 || (data[0] != '0' && data[0] != '1') || data[1] != ',' || data[5] != ',') {
      return false;
    }

    uint16_t steering = 0;
    uint16_t throttle = 0;
    for (uint8_t index = 2; index < 5; ++index) {
      if (data[index] < '0' || data[index] > '9') {
        return false;
      }
      steering = steering * 10 + static_cast<uint16_t>(data[index] - '0');
    }
    for (uint8_t index = 6; index < 9; ++index) {
      if (data[index] < '0' || data[index] > '9') {
        return false;
      }
      throttle = throttle * 10 + static_cast<uint16_t>(data[index] - '0');
    }
    if (steering > 255 || throttle > 255) {
      return false;
    }

    AUTO_READY = data[0] == '1';
    CMD_STEERING = static_cast<uint8_t>(steering);
    CMD_THROTTLE = static_cast<uint8_t>(throttle);
    return true;
  }

} FromJetson;

typedef struct {
  bool ESTOP{false};
  bool AUTO_ARM{false};
  bool MANUAL_START{false};
  Mode MODE{Mode::ESTOP};
  uint8_t BATTERY_LEVEL{255};

  bool serialize(uint8_t* buffer, uint8_t bufferSize) {
    // Need enough space for max size values with comma delimiter and trailing
    // '\n' and '\0'
    if (bufferSize < 14) {
      return false;
    }

    ::serialize(ESTOP, &buffer);
    ::serialize(AUTO_ARM, &buffer);
    ::serialize(MANUAL_START, &buffer);
    ::serialize(MODE, &buffer);
    ::serialize(BATTERY_LEVEL, &buffer);
    *buffer = '\n';
    ++(buffer);
    *buffer = '\0';
    ++(buffer);
    return true;
  }

} ToJetson;

// Helpers

bool IsTimedOut(unsigned long latestUpdate, unsigned long sampleTime, unsigned long timeout) {
  // Handle 32-bit rollover
  if (latestUpdate > sampleTime) {
    return (0xFFFFFFFFUL - latestUpdate + sampleTime) >= timeout;
  }
  return (sampleTime - latestUpdate) >= timeout;
}

uint8_t GetPacketSize(uint8_t* buffer, uint8_t bufferSize, char endChar = '\n') {
  uint8_t length = 0;
  while (length < bufferSize) {
    if (buffer[length] == endChar) {
      return length + 1;
    }
    ++length;
  }
  return length;
}

bool IsNearlyCenter(uint8_t value, uint8_t centerValue = 127, uint8_t tolerance = 5) {
  if (centerValue < tolerance) {
    return value <= (centerValue + tolerance);
  } else if ((255 - centerValue) < tolerance) {
    return value >= (centerValue - tolerance);
  }
  return (value >= (centerValue - tolerance)) && (value <= (centerValue + tolerance));
}

struct XBeeRx16Parser {
  static const uint8_t maxFrameLength = 64;

  enum class State : uint8_t { WAIT_START, LENGTH_MSB, LENGTH_LSB, FRAME };

  State state{State::WAIT_START};
  uint8_t frameData[maxFrameLength];
  uint16_t frameLength{0};
  uint8_t frameIndex{0};
  uint8_t checksum{0};
  bool escaped{false};

  void reset() {
    state = State::WAIT_START;
    frameLength = 0;
    frameIndex = 0;
    checksum = 0;
    escaped = false;
  }

  bool readFrame(uint8_t*& payload, uint8_t& payloadLength) {
    uint8_t bytesRead = 0;
    while (serXBee.available() && bytesRead < 16) {
      uint8_t value = serXBee.read();
      ++bytesRead;

      if (state == State::WAIT_START) {
        if (value == START_BYTE) {
          state = State::LENGTH_MSB;
        }
        continue;
      }

      if (escaped) {
        value ^= 0x20;
        escaped = false;
      } else if (value == ESCAPE) {
        escaped = true;
        continue;
      } else if (value == START_BYTE) {
        reset();
        state = State::LENGTH_MSB;
        continue;
      }

      switch (state) {
        case State::LENGTH_MSB:
          frameLength = static_cast<uint16_t>(value) << 8;
          state = State::LENGTH_LSB;
          break;
        case State::LENGTH_LSB:
          frameLength |= value;
          if (frameLength == 0 || frameLength > maxFrameLength) {
            reset();
          } else {
            frameIndex = 0;
            checksum = 0;
            state = State::FRAME;
          }
          break;
        case State::FRAME:
          if (frameIndex < frameLength) {
            frameData[frameIndex++] = value;
            checksum += value;
            break;
          }

          {
            const bool valid =
                static_cast<uint8_t>(checksum + value) == 0xFF && frameData[0] == RX_16_RESPONSE && frameLength >= 5;
            if (valid) {
              payload = frameData + 5;
              payloadLength = frameLength - 5;
            }
            reset();
            if (valid) {
              return true;
            }
          }
          break;
        case State::WAIT_START:
          break;
      }
    }
    return false;
  }
};

XBeeRx16Parser xbeeRxParser;

// Caps max throttle deflection to 1/4 of full scale (25%) in both directions.
// Chosen because it evenly divides the *4 us-per-count step below, so the
// full 8-bit input resolution survives the scale-down with no rounding loss.
constexpr uint8_t THROTTLE_SCALE_DIVISOR = 4;

// Deadband around center [125,130].  Overall pulse range [1000us,2000us],
// narrowed around 1500us by scaleDivisor.
int PctToPulseLength(uint8_t throttle, bool deadband = true, uint8_t scaleDivisor = 1) {
  if (deadband) {
    if (throttle > 130) {
      return 1500 + ((throttle - 130) * 4) / scaleDivisor;
    } else if (throttle < 125) {
      return 1500 + ((throttle - 124) * 4) / scaleDivisor;
    }
    return 1500;
  } else {
    // Some saturation at min and max values
    return constrain(((static_cast<int>(throttle) - 127) * 4) / scaleDivisor + 1500, 1000, 2000);
  }
}

// Main Code

void setup() {
  xbee = XBee();

  // Setup USB serial
  Serial.begin(1000000);
  while (!Serial) {
    ;  // wait for serial port to connect
  }
  Serial.setTimeout(1);

  serXBee.begin(57600);
  while (!serXBee) {
    ;  // wait for serial port to connect
  }
  xbee.setSerial(serXBee);
  tx16.setFrameId(NO_RESPONSE_FRAME_ID);

  // Throttle to FL(10, OC1B), Steering to RL(9, OC1A)
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  // Fast PWM, TOP=ICR1 (mode 14), non-inverting on OC1A/OC1B, prescaler /8
  TCCR1A = _BV(COM1A1) | _BV(COM1B1) | _BV(WGM11);
  TCCR1B = _BV(WGM13) | _BV(WGM12) | _BV(CS11);
  ICR1 = PWM_PERIOD_TICKS - 1;
  OCR1A = PulseUsToTicks(1500);  // steering, centered
  OCR1B = PulseUsToTicks(1500);  // throttle, centered
}

void loop() {
  static FromOffboard offboardState;
  static FromJetson jetsonState;
  static unsigned long latestOffboardUpdate = 0;
  static unsigned long latestJetsonUpdate = 0;
  static bool offboardTimedOut = true;
  static bool jetsonTimedOut = true;
  static Mode autoMode = Mode::ESTOP;

  const auto now = millis();
  static auto lastXBeeTx = now;
  static auto lastOnboardTx = now;
  static uint16_t xbeeFrames = 0;
  static uint16_t xbeeRx16Frames = 0;
  static uint16_t xbeeValidMessages = 0;
  static uint16_t xbeeInvalidMessages = 0;
  static uint16_t validJetsonFrames = 0;
  static uint16_t invalidJetsonFrames = 0;
  static uint8_t lastRejectedJetsonFrame[sizeof(onboardRxPayload)] = {};
  static uint8_t lastRejectedJetsonFrameLength = 0;
  bool receivedOffboardMessage = false;

  // Offboard Rx
  uint8_t* offboardPayload = nullptr;
  uint8_t offboardPayloadLength = 0;
  if (xbeeRxParser.readFrame(offboardPayload, offboardPayloadLength)) {
    ++xbeeFrames;
    ++xbeeRx16Frames;
    if (offboardState.deSerialize(offboardPayload, offboardPayloadLength)) {
      ++xbeeValidMessages;
      latestOffboardUpdate = now;
      receivedOffboardMessage = true;
    } else {
      ++xbeeInvalidMessages;
    }
  }

  // Onboard Rx.  Serial.readBytesUntil() returns a partial buffer when its
  // timeout expires.  Those fragments can still look like a valid three-field
  // command (for example "1,127,0" from a frame whose last digits have not
  // arrived), which turns USB packet timing into actuator noise.  Only parse
  // complete newline-terminated frames.
  static uint8_t onboardRxLength = 0;
  static bool onboardRxDiscarding = false;
  while (Serial.available() > 0) {
    const int received = Serial.read();
    if (received == '\r') {
      continue;
    }
    if (received == '\n') {
      if (!onboardRxDiscarding && onboardRxLength > 0) {
        // Decode into a candidate first.  A malformed frame must not mutate
        // the command that remains live until the USB watchdog expires.
        FromJetson candidate;
        if (candidate.deSerialize(onboardRxPayload, onboardRxLength)) {
          jetsonState = candidate;
          latestJetsonUpdate = now;
          ++validJetsonFrames;
        } else {
          ++invalidJetsonFrames;
          CopyRejectedJetsonFrame(
              onboardRxPayload, onboardRxLength, lastRejectedJetsonFrame, lastRejectedJetsonFrameLength);
        }
      } else if (onboardRxLength > 0) {
        ++invalidJetsonFrames;
        CopyRejectedJetsonFrame(
            onboardRxPayload, onboardRxLength, lastRejectedJetsonFrame, lastRejectedJetsonFrameLength);
      }
      onboardRxLength = 0;
      onboardRxDiscarding = false;
      continue;
    }
    if (onboardRxDiscarding) {
      continue;
    }
    if (onboardRxLength < sizeof(onboardRxPayload)) {
      onboardRxPayload[onboardRxLength++] = static_cast<uint8_t>(received);
    } else {
      // Drop the whole oversized frame rather than parsing its suffix as a
      // new command on the next loop iteration.
      onboardRxLength = 0;
      onboardRxDiscarding = true;
      ++invalidJetsonFrames;
      CopyRejectedJetsonFrame(
          onboardRxPayload, sizeof(onboardRxPayload), lastRejectedJetsonFrame, lastRejectedJetsonFrameLength);
    }
  }

  if (IsTimedOut(latestOffboardUpdate, now, commsTimeout_ms)) {
    offboardState = FromOffboard();
    if (!offboardTimedOut) {
      serXBee.stopListening();
      serXBee.listen();
      xbeeRxParser.reset();
    }
    offboardTimedOut = true;
  } else {
    offboardTimedOut = false;
  }

  if (IsTimedOut(latestJetsonUpdate, now, commsTimeout_ms)) {
    jetsonState = FromJetson();
    jetsonTimedOut = true;
  } else {
    jetsonTimedOut = false;
  }

  // State management
  if (offboardState.ESTOP || offboardTimedOut) {
    autoMode = Mode::ESTOP;
  } else if (offboardState.AUTO_ARM == false && autoMode != Mode::RC_ACTIVE) {
    autoMode = Mode::RC_ARMED;
  } else if (offboardState.AUTO_ARM && autoMode != Mode::AUTO_ACTIVE) {
    autoMode = Mode::AUTO_ARMED;
  }

  switch (autoMode) {
    case Mode::ESTOP:
      break;
    case Mode::RC_ARMED:
      if (offboardState.RC_PRESENT && IsNearlyCenter(offboardState.AXIS_LY) && IsNearlyCenter(offboardState.AXIS_LX)) {
        autoMode = Mode::RC_ACTIVE;
      }
      break;
    case Mode::RC_ACTIVE:
      break;
    case Mode::AUTO_ARMED:
      if (jetsonState.AUTO_READY && IsNearlyCenter(jetsonState.CMD_STEERING) &&
          IsNearlyCenter(jetsonState.CMD_THROTTLE)) {
        autoMode = Mode::AUTO_ACTIVE;
      }
      break;
    case Mode::AUTO_ACTIVE:
      // AUTO_READY is an enable, not only an entry-handshake signal.  Leaving
      // AUTO_ACTIVE as soon as the Jetson clears it guarantees neutral PWM
      // between path goals while the serial link remains healthy.
      if (jetsonTimedOut || !jetsonState.AUTO_READY) {
        autoMode = Mode::AUTO_ARMED;
      }
      break;
  }

  // Car control
  auto throttleCmd = PctToPulseLength(127);
  auto steeringCmd = PctToPulseLength(127);

  switch (autoMode) {
    case Mode::RC_ACTIVE:
      throttleCmd = PctToPulseLength(255 - offboardState.AXIS_LY, true, THROTTLE_SCALE_DIVISOR);
      steeringCmd = PctToPulseLength(offboardState.AXIS_RX);
      break;
    case Mode::AUTO_ACTIVE:
      throttleCmd = PctToPulseLength(jetsonState.CMD_THROTTLE, false, THROTTLE_SCALE_DIVISOR);
      // Convention is positive left for right hand rule
      steeringCmd = PctToPulseLength(255 - jetsonState.CMD_STEERING, false);
      break;
    default:
      throttleCmd = PctToPulseLength(127);
      steeringCmd = PctToPulseLength(127);
  }

  OCR1B = PulseUsToTicks(throttleCmd);
  OCR1A = PulseUsToTicks(steeringCmd);

  /// @todo Read battery level
  uint8_t batteryLevel = 255;

  ToJetson onboardFeedback;
  onboardFeedback.ESTOP = offboardState.ESTOP;
  onboardFeedback.AUTO_ARM = offboardState.AUTO_ARM;
  onboardFeedback.MANUAL_START = offboardState.MANUAL_START;
  onboardFeedback.MODE = autoMode;
  onboardFeedback.BATTERY_LEVEL = batteryLevel;
  onboardFeedback.serialize((uint8_t*)onboardTxPayload, sizeof(onboardTxPayload));

  ToOffboard offboardFeedback;
  offboardFeedback.MODE = autoMode;
  offboardFeedback.BATTERY_LEVEL = batteryLevel;
  offboardFeedback.STEERING_OUTPUT_US = steeringCmd;
  offboardFeedback.THROTTLE_OUTPUT_US = throttleCmd;
  offboardFeedback.serialize((uint8_t*)offboardTxPayload, sizeof(offboardTxPayload));

  // Transmit immediately after a valid offboard frame. SoftwareSerial disables
  // receive interrupts while transmitting, so this avoids colliding with the
  // next 20 Hz command frame.
  if (receivedOffboardMessage && now - lastXBeeTx >= 50) {
    // Offboard Tx
    // tx16.setAddress16(rx16.getRemoteAddress16());
    tx16.setAddress16(0);
    tx16.setPayload(offboardTxPayload, GetPacketSize(offboardTxPayload, sizeof(offboardTxPayload)));
    if (enableOffboardTx) {
      xbee.send(tx16);
    }
    lastXBeeTx = now;
  }

  if (now - lastOnboardTx >= 50) {
    Serial.write(onboardTxPayload, GetPacketSize(onboardTxPayload, sizeof(onboardTxPayload)));
    if (enableOnboardDebug) {
      char rejectedHex[sizeof(lastRejectedJetsonFrame) * 2 + 1] = {};
      EncodeHex(lastRejectedJetsonFrame, lastRejectedJetsonFrameLength, rejectedHex);
      // This uses a distinct prefix so it cannot be mistaken for the normal
      // five-field status frame consumed by the Jetson bridge.
      const int debugLength = snprintf(reinterpret_cast<char*>(onboardDebugPayload),
                                       sizeof(onboardDebugPayload),
                                       "D,%lu,%u,%u,%u,%u,%u,%u,%u,%u,%u,%s\n",
                                       now,
                                       validJetsonFrames,
                                       invalidJetsonFrames,
                                       jetsonState.AUTO_READY,
                                       jetsonState.CMD_STEERING,
                                       jetsonState.CMD_THROTTLE,
                                       static_cast<uint8_t>(autoMode),
                                       steeringCmd,
                                       throttleCmd,
                                       lastRejectedJetsonFrameLength,
                                       rejectedHex);
      if (debugLength > 0 && debugLength < static_cast<int>(sizeof(onboardDebugPayload))) {
        Serial.write(onboardDebugPayload, static_cast<size_t>(debugLength));
      }
    }
    lastOnboardTx = now;
  }
}
